import {
  ProviderContact as IProviderContact,
  Provider as IProvider,
  User as IUser,
} from "./autogenerated-interfaces/app";
import {
  Case as ICase,
  Client as IClient,
  Applicant as IApplicant,
  CaseStepContract as ICaseStepContract,
  Move as IMove,
} from "./autogenerated-interfaces/client";
import {
  Country as ICountry,
  ProcessRuleSet as IProcess,
  Route as IRoute,
} from "./autogenerated-interfaces/immigration";

export function NullCountry(): ICountry {
  return {
    uuid: "",
    name: "",
    code: "",
    currency_code: "",
    unicode_flag: "",
  };
}

export function NullRoute(): IRoute {
  return {
    name: "",
    host_country: NullCountry(),
  };
}

function NullProcess(): IProcess {
  return {
    id: 0,
    uuid: "",
    route: NullRoute(),
    steps: [],
    step_rulesets: [],
    nationalities: [],
    home_countries: [],
    intra_company_moves_only: false,
  };
}

function NullUser(): IUser {
  return { uuid: "", email: "", first_name: "", last_name: "" };
}

function NullClient(): IClient {
  return { uuid: "", name: "" };
}

export function NullApplicant(): IApplicant {
  return {
    id: 0,
    uuid: "",
    user: NullUser(),
    employer: NullClient(),
    home_country: NullCountry(),
    nationalities: [],
  };
}

export function NullMove(): IMove {
  return {
    host_country: NullCountry(),
    target_entry_date: "",
    target_exit_date: "",
  };
}

export function NullProvider(): IProvider {
  return {
    uuid: "",
    logo_url: "",
    name: "",
  };
}

export function NullProviderContact(): IProviderContact {
  return {
    uuid: "",
    user: NullUser(),
    provider: NullProvider(),
  };
}

export function NullCase(): ICase {
  return {
    uuid: undefined,
    applicant: NullApplicant(),
    move: NullMove(),
    process: NullProcess(),
    steps: [],
  };
}

export function NullCaseStepContract(): ICaseStepContract {
  return {
    provider_contact: NullProviderContact(),
  };
}

// TODO: better options here?

export function countryIsNull(country: ICountry): boolean {
  return !country.code;
}

export function processIsNull(process: IProcess): boolean {
  return routeIsNull(process.route);
}

export function routeIsNull(route: IRoute): boolean {
  return !route.name || countryIsNull(route.host_country);
}
export function userIsNull(user: IUser): boolean {
  return !user.first_name;
}

export function applicantIsNull(applicant: IApplicant): boolean {
  return userIsNull(applicant.user);
}

export function providerContactIsNull(
  providerContact: IProviderContact
): boolean {
  return userIsNull(providerContact.user);
}
