import { StoredFileSerializer } from "./autogenerated-interfaces";

export class VueFileAgentFileRecord {
  name: string;
  size: number;
  type: string;

  constructor(storedFile: StoredFileSerializer) {
    this.name = storedFile.name;
    this.size = storedFile.size;
    this.type = storedFile.media_type;
  }
}
