import { StoredFile as IStoredFile } from "./autogenerated-interfaces/app";

export class VueFileAgentFileRecord {
  name: string;
  size: number;
  type: string;

  constructor(storedFile: IStoredFile) {
    this.name = storedFile.name;
    this.size = storedFile.size;
    this.type = storedFile.media_type;
  }
}
