# Generated by Django 3.2 on 2021-05-06 18:02

from django.db import migrations
import owldock.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='process_uuid',
            field=owldock.models.fields.UUIDPseudoForeignKeyField('immigration.ProcessRuleSet', db_index=True, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='process_step_uuid',
            field=owldock.models.fields.UUIDPseudoForeignKeyField('immigration.ProcessStep', db_index=True, to_field='uuid'),
        ),
    ]
