<template>
  <b-button
    @click="click()"
    :type="type"
    :disabled="disabled"
    :loading="loading"
  >
    {{ action.display_name }}
  </b-button>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { ActionSerializer } from "../autogenerated-interfaces";
import http from "../http";

export default Vue.extend({
  props: {
    // `action` contains a URL for the endpoint performing this action. The id
    // of the object to be operated on is encoded in the URL.
    action: Object as PropType<ActionSerializer>,
    // `object` is the client-side state of the object to be operated on. Some
    // endpoints will use this as a source of additional arguments for the
    // action. For example, when offering CaseStep S _to_ Provider P, the id of
    // S is encoded in the URL, but the id of P will be taken from the
    // client-side state of S.
    object: Object,
  },

  data() {
    return {
      type: "is-warning is-light",
      disabled: false,
      loading: false,
    };
  },

  methods: {
    async click(): Promise<void> {
      const response = await http.post(this.action.url, {
        body: JSON.stringify(this.object),
      });
      this.loading = true;
      if (!response.ok) {
        this.type = "is-danger is-light";
      } else {
        const obj = await response.json();
        // TODO: what is our protocol for identifying an error response?
        if (obj && obj.errors) {
          this.type = "is-danger is-light";
        } else {
          this.type = "is-success is-light";
          this.disabled = true;
          this.$emit("action:success", obj);
        }
      }
      this.loading = false;
    },
  },
});
</script>

<style scoped>
</style>