<template>
  <b-button @click="click()" :type="type" :loading="loading" outlined>
    {{ action.display_name }}
  </b-button>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { ActionSerializer } from "../autogenerated-interfaces";
import http from "../http";
import { showMessages } from "../server-messages";

export default Vue.extend({
  props: {
    // `action` contains a URL for the endpoint performing this action. The id
    // of the object to be operated on is encoded in the URL.
    action: Object as PropType<ActionSerializer>,
    // `object` is the client-side state of the object to be operated on. Some
    // endpoints will use this as a source of additional arguments for the
    // action. For example, when offering CaseStep S _to_ Provider P, the id of
    // S is encoded in the URL, but the id of P will be taken from the
    // client-side state of S.
    object: Object,
  },

  data() {
    return {
      type: "is-info is-light",
      loading: false,
    };
  },

  methods: {
    async click(): Promise<void> {
      const httpResponse = await http.post(this.action.url, {
        body: JSON.stringify(this.object),
      });
      this.loading = true;
      if (!httpResponse.ok) {
        this.type = "is-danger is-light";
      } else {
        const response = await httpResponse.json();
        showMessages(response);
        if (response && response.errors.length > 0) {
          this.type = "is-danger is-light";
        } else {
          this.type = "is-success is-light";
          this.$emit("action:success", response.data);
        }
      }
      this.loading = false;
    },
  },
});
</script>

<style scoped></style>
