<template>
  <div class="media">
    <div class="media-left">
      <figure
        class="image is-4x3"
        v-for="nationality of applicant.nationalities"
        :key="nationality.code"
      >
        <country :country="nationality" />
      </figure>
    </div>

    <div class="media-content">
      <p class="title is-size-6">
        {{ applicant.user.first_name }}
        {{ applicant.user.last_name }}
      </p>
      <p class="subtitle is-size-6">
        <span v-if="mailto">
          <a :href="`mailto:${applicant.user.email}`" target="#">
            {{ applicant.user.email }}
          </a>
        </span>
      </p>
    </div>
    <i v-if="applicantEditable" class="fas fa-pencil-alt"></i>
  </div>
</template>

<script lang="ts">
import { ApplicantSerializer } from "@/autogenerated-interfaces";
import Vue, { PropType } from "vue";

import Country from "./Country.vue";

export default Vue.extend({
  components: { Country },
  props: {
    applicant: Object as PropType<ApplicantSerializer>,
    applicantEditable: Boolean,
    mailto: { type: Boolean, default: false },
  },
});
</script>

<style scoped>
a,
a:hover {
  color: currentColor;
}
</style>
