<template>
  <div class="field has-addons" style="width: 100%">
    <p class="control" style="width: 100%">
      <b-field :label="label">
        <b-autocomplete
          ref="autocomplete"
          v-model="input"
          field="displayName"
          :data="filteredCandidates"
          @select="(applicant) => $emit('change:applicant', applicant)"
          :openOnFocus="true"
          dropdown-position="bottom"
          max-height="100vh"
        >
          <template slot-scope="props">
            {{ props.option.flags }} {{ props.option.displayName }}
          </template>
        </b-autocomplete>
      </b-field>
    </p>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { ApplicantSerializer } from "../autogenerated-interfaces";
import { inputMatchesString } from "@/utils";
import { dismissMobileKeyboardOnDropdownScroll } from "../componentUtils";
import { applicantUnicodeFlags } from "../methods";
import http from "../http";

export default Vue.extend({
  props: { label: String },

  data() {
    return {
      applicants: [] as ApplicantSerializer[],
      input: "",
    };
  },

  created() {
    http
      .get("/api/client-contact/applicants/")
      .then((resp) => resp.json())
      .then((data) => (this.applicants = data));
  },

  mounted() {
    dismissMobileKeyboardOnDropdownScroll(this, "autocomplete");
  },

  computed: {
    filteredCandidates(): ApplicantSerializer[] {
      return this.applicants
        .filter((applicant) =>
          inputMatchesString(this.input, displayName(applicant))
        )
        .map((applicant) => {
          return Object.assign(applicant, {
            displayName: displayName(applicant),
            flags: applicantUnicodeFlags(applicant),
          });
        });
    },
  },
});

function displayName(applicant: ApplicantSerializer): string {
  return `${applicant.user.first_name} ${applicant.user.last_name}`;
}
</script>
