<template>
  <div>
    <div class="card" style="overflow: visible">
      <case-table
        :rows="[case_]"
        :casesEditable="[caseEditable]"
        :showProviders="true"
        :focusable="false"
        :paginated="false"
      />
    </div>

    <div
      v-if="case_ && haveProcess"
      class="card mt-6"
      style="overflow: visible"
    >
      <div class="card-content">
        <process :case_="case_" :showSteps="showSteps" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import CaseTable from "./CaseTable.vue";
import Process from "./Process.vue";
import { CaseSerializer } from "../autogenerated-interfaces";
import { processIsNull } from "../factories";

export default Vue.extend({
  props: {
    case_: Object as PropType<CaseSerializer>,
    caseEditable: Object,
    showSteps: { type: Boolean, default: true },
  },

  components: {
    CaseTable,
    Process,
  },

  computed: {
    haveProcess(): boolean {
      return !processIsNull(this.case_.process);
    },
  },
});
</script>
