<template>
  <b-table :data="steps" detailed :show-detail-icon="false">
    <b-table-column label="Step" v-slot="props">
      {{ props.row.sequence_number }}. {{ props.row.process_step.service.name }}
    </b-table-column>

    <b-table-column label="Provider" v-slot="props">
      <provider-contact
        v-if="props.row.active_contract && props.row.active_contract.provider_contact"
        :provider_contact="props.row.active_contract.provider_contact"
        class="mr-3"
      >
      </provider-contact>
      <div v-else>[No provider contact assigned]</div>
    </b-table-column>

    <b-table-column label="Status" v-slot="props">
      {{ props.row.state }}
    </b-table-column>

    <b-table-column v-slot="props">
      <template>
        <a @click="props.toggleDetails(props.row)"> Manage files </a>
      </template>
    </b-table-column>

    <template #detail="props">
      <case-step-file-upload-area :step="props.row">
      </case-step-file-upload-area>
    </template>
  </b-table>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import CaseStepFileUploadArea from "./CaseStepFileUploadArea.vue";
import ProviderContact from "../components/ProviderContact.vue";
import { CaseStepSerializer } from "../autogenerated-interfaces";

export default Vue.extend({
  components: { CaseStepFileUploadArea, ProviderContact },

  props: { steps: Array as PropType<CaseStepSerializer[]> },
});
</script>

<style scoped>
a,
a:hover {
  color: currentColor;
  text-decoration: underline;
}
</style>