<template>
  <div v-if="state === State.Displaying" @click="handleClick">
    <provider
      :provider="caseStep.active_contract.provider_contact.provider"
      :showName="false"
    />
  </div>
  <provider-contact-selector
    v-else
    ref="providerContactSelector"
    placeholder="Select Provider"
    :process="process"
    :giveAppearanceOfSelectingProvider="true"
    :initialProviderContacts="providerContacts"
    @select:provider-contact="handleSelectProviderContact"
    @blur="state = State.Displaying"
  />
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { BAutocomplete } from "buefy/src/components/autocomplete";

import {
  CaseStepSerializer,
  ProcessSerializer,
  ProviderContactSerializer,
} from "../autogenerated-interfaces";
import Provider from "./Provider.vue";
import ProviderContactSelector from "./ProviderContactSelector.vue";
import { NullCaseStepContract } from "@/factories";
import { isClientContact } from "../role";

type ProviderContactSelectorType = InstanceType<typeof ProviderContactSelector>;
type BAutocompleteType = InstanceType<typeof BAutocomplete>;

enum State {
  Displaying,
  Selecting,
}

export default Vue.extend({
  props: {
    caseStep: Object as PropType<CaseStepSerializer>,
    process: Object as PropType<ProcessSerializer>,
    providerContacts: Array as PropType<ProviderContactSerializer[]>,
  },

  components: {
    Provider,
    ProviderContactSelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
    };
  },

  created() {
    if (this.hasProviderContact) {
      this.state = State.Displaying;
    }
  },

  computed: {
    hasProviderContact(): boolean {
      return Boolean(
        this.caseStep.active_contract &&
          this.caseStep.active_contract.provider_contact
      );
    },

    canChangeProviderContact(): boolean {
      if (!isClientContact()) {
        return false;
      }
      for (let action of this.caseStep.actions) {
        if (action.name == "client_contact_earmark_case_step") {
          return true;
        }
      }
      return false;
    },
  },

  methods: {
    handleSelectProviderContact(providerContact: ProviderContactSerializer) {
      const caseStep = Object.assign({}, this.caseStep);
      if (!caseStep.active_contract) {
        caseStep.active_contract = NullCaseStepContract();
      }
      caseStep.active_contract.provider_contact = providerContact;
      this.$emit("update:case-step", caseStep);
      this.state = State.Displaying;
    },

    handleClick() {
      if (this.state === State.Displaying) {
        if (this.canChangeProviderContact) {
          this.state = State.Selecting;
          this.$nextTick(() => {
            const providerContactSelector = this.$refs
              .providerContactSelector as ProviderContactSelectorType;
            const autocomplete: BAutocompleteType =
              providerContactSelector.$refs.autocomplete;
            const input: HTMLElement = autocomplete.$refs.input.$refs.input;
            input.focus();
          });
        }
      }
    },
  },
});
</script>

<style scoped>
</style>