  <template>
  <div>
    <section class="section">
      <case :case_="case_" :caseEditable="caseEditable" :showClient="false" />

      <div class="form pt-6">
        <fieldset>
          <div class="field is-grouped pt-4">
            <div class="control">
              <button
                class="button is-link"
                ref="submitButton"
                @click="handleSubmit"
              >
                Submit
              </button>
            </div>
          </div>
        </fieldset>
      </div>
      <div>
        <vue-json-pretty
          v-if="validationErrors"
          :path="'res'"
          :data="validationErrors"
          class="mt-4"
        >
        </vue-json-pretty>
      </div>
    </section>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

import VueJsonPretty from "vue-json-pretty";
import "vue-json-pretty/lib/styles.css";
import { NotificationProgrammatic as Notification } from "buefy";

import {
  CountrySerializer,
  ApplicantSerializer,
  ProcessSerializer,
  ProviderContactSerializer,
} from "../autogenerated-interfaces";
import Case from "../components/Case.vue";
import {
  NullCase,
  applicantIsNull,
  processIsNull,
  NullProviderContact,
} from "@/factories";
import http from "../http";
import { showMessages } from "../server-messages";
import { dateToYYYYMMDD } from "../utils";
import eventBus from "@/event-bus";

export default Vue.extend({
  components: {
    Case,
    VueJsonPretty,
  },

  data() {
    return {
      case_: NullCase(),
      caseEditable: {
        applicant: true,
        country: true,
        dateRange: true,
        provider: true,
        route: true,
        steps: { provider: true },
      },
      input: {
        route: "",
      },
      // All processes matching country, applicant nationalities & home country, dates
      processes: [] as ProcessSerializer[],
      // Subset of those processes matching selected route
      validationErrors: null as object | null,
      // Provider contacts are linked indendently to each case step; the case
      // itself does not have a provider contact. However, the form gives the
      // appearance to the user that they are selecting a single provider
      // contact for the case. This is stored in the following value, and is
      // copied to each of the case steps.
      defaultProviderContact: NullProviderContact() as ProviderContactSerializer,
    };
  },

  created() {
    // TODO: This global event bus is a bit sketchy. What about if something
    // else is changing a country for some other reason?
    eventBus.$on("update:applicant", this.handleChangeApplicant);
    eventBus.$on("update:country", this.handleChangeHostCountry);
    eventBus.$on("update:provider-contact", this.handleSelectProviderContact);
    eventBus.$on("update:process", this.handleChangeProcess);
  },

  computed: {
    haveApplicant(): boolean {
      return !applicantIsNull(this.case_.applicant);
    },

    haveProcess(): boolean {
      return !processIsNull(this.case_.process);
    },
  },

  methods: {
    handleChangeApplicant(applicant: ApplicantSerializer) {
      if (!applicant) {
        // FIXME: why
        console.log("ERROR: applicant is", JSON.stringify(applicant));
        return;
      }
      this.case_.applicant = applicant;
    },

    // FIXME: this is updating the processes to match country, nationality, home
    // country, dates, so it needs to be triggered accordingly.
    async handleChangeHostCountry(country: CountrySerializer) {
      if (!country) {
        // FIXME: why
        console.log("ERROR: country is", JSON.stringify(country));
        return;
      }
      this.case_.process.route.host_country = country;
      if (this.case_.applicant.nationalities) {
        const nationalityCodes = this.case_.applicant.nationalities.map(
          (country) => country.code
        );
        this.processes =
          (await http.fetchDataOrNull(
            `/api/processes/?host_country=${
              country.code
            }&nationalities=${nationalityCodes.join(",")}`
          )) || [];
        eventBus.$emit("update:candidate-processes", this.processes);
      }
    },

    handleChangeProcess(process: ProcessSerializer): void {
      this.case_.process = process;
      // Create case steps as a copy of process steps; set provider contact on
      // each step to the provider contact that the user has chosen (or the
      // initial null value).
      this.case_.steps = process.steps.map((s, i) => ({
        active_contract: {
          provider_contact: this.defaultProviderContact,
        },
        // TODO: Use enum labels instead of display names
        state: {
          name: "FREE",
          value: "Waiting for user to notify provider",
        },
        actions: [],
        process_step: s,
        sequence_number: i + 1,
        stored_files: [],
      }));
      // Changing the steps often makes a large difference to the vertical
      // height of the Case component at the top of the page.
      const submitButton = this.$refs.submitButton as HTMLElement;
      this.$nextTick(() => submitButton.scrollIntoView());
    },

    handleSelectProviderContact(
      providerContact: ProviderContactSerializer
    ): void {
      this.defaultProviderContact = providerContact;
      for (let step of this.case_.steps) {
        step.active_contract.provider_contact = providerContact;
      }
    },

    handleInputDateRange([entryDate, exitDate]: [Date, Date]): void {
      this.case_.target_entry_date = dateToYYYYMMDD(entryDate);
      this.case_.target_exit_date = dateToYYYYMMDD(exitDate);
    },

    async handleSubmit(): Promise<void> {
      // TODO: validation
      const httpResponse = await http.post("/api/client-contact/create-case/", {
        body: JSON.stringify(this.case_),
      });
      if (httpResponse.ok) {
        const response = await httpResponse.json();
        showMessages(response);
        if (response.errors.length > 0) {
          this.validationErrors = response.errors;
        } else {
          const message = `Success! Case created for ${this.case_.applicant.user.first_name} ${this.case_.applicant.user.last_name}.`;
          Notification.open({
            message,
            type: "is-success",
            hasIcon: true,
            position: "is-bottom-right",
          });
          this.case_ = NullCase();
          this.$router.push("/portal/cases/");
        }
      }
    },
  },
});
</script>


