<template>
  <b-table ref="table" :data="steps" detailed :show-detail-icon="false">
    <b-table-column label="Step" v-slot="props">
      <span class="has-text-weight-bold">
        {{ props.row.sequence_number }}.
        {{ props.row.process_step.name }}
      </span>
    </b-table-column>

    <b-table-column label="Provider" width="420" v-slot="props">
      <editable-case-step-provider
        :caseStep="props.row"
        :editingSpec="editingSpec.provider"
        :process="process"
        @update:case-step="(caseStep) => updateRow(props.index, caseStep)"
      />
    </b-table-column>

    <b-table-column label="Contact" v-slot="props">
      <provider-contact
        v-if="
          props.row.active_contract &&
          props.row.active_contract.provider_contact
        "
        :provider_contact="props.row.active_contract.provider_contact"
      />
    </b-table-column>

    <b-table-column label="Status" v-slot="props">
      {{ props.row.state.value }}
    </b-table-column>

    <b-table-column label="Actions" v-slot="props">
      <ul>
        <li v-for="action of props.row.actions" :key="action.url">
          <action-button
            class="mb-2"
            :action="action"
            :object="props.row"
            @action:success="(caseStep) => updateRow(props.index, caseStep)"
          >
          </action-button>
        </li>
      </ul>
    </b-table-column>

    <b-table-column v-slot="props">
      <template>
        <a @click="props.toggleDetails(props.row)"> Manage files </a>
      </template>
    </b-table-column>

    <template #detail="props">
      <case-step-file-upload-area :step="props.row">
      </case-step-file-upload-area>
    </template>
  </b-table>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import BTable from "buefy/src/components/table";
type BTableInstance = InstanceType<typeof BTable>;

import ActionButton from "./ActionButton.vue";
import CaseStepFileUploadArea from "./CaseStepFileUploadArea.vue";
import EditableCaseStepProvider from "./EditableCaseStepProvider.vue";
import ProviderContact from "../components/ProviderContact.vue";
import { EditingSpec } from "@/editable-component";
import { CaseStep as ICaseStep } from "../autogenerated-interfaces/client";
import { ProcessRuleSet as IProcess } from "../autogenerated-interfaces/immigration";
import eventBus from "../event-bus";

export default Vue.extend({
  components: {
    ActionButton,
    CaseStepFileUploadArea,
    EditableCaseStepProvider,
    ProviderContact,
  },

  props: {
    steps: Array as PropType<ICaseStep[]>,
    process: Object as PropType<IProcess>,
    editingSpec: Object as PropType<{ provider: EditingSpec }>,
  },

  methods: {
    updateRow(index: number, caseStep: ICaseStep | null) {
      // The table data seems to be a copy of the real case.steps data. So we
      // need to do two things:

      // 1. Emit an event that the owner of the case.steps data can respond to
      //    by mutating its copy
      eventBus.$emit("update:case-step", index, caseStep);

      // 2. Mutate our copy
      const table = this.$refs.table as BTableInstance;
      if (caseStep) {
        table.visibleData.splice(index, 1, caseStep);
      } else {
        table.visibleData.splice(index, 1);
      }
    },
  },
});
</script>

<style scoped>
a,
a:hover {
  color: currentColor;
  text-decoration: underline;
}
</style>
