<template>
  <div>
    <div class="card" style="overflow: visible">
      <case-table :rows="[case_]" :showProviders="false" :paginated="false" />
    </div>

    <div class="card mt-6" style="overflow: visible">
      <div class="card-content">
        <process
          v-if="case_ && haveProcess"
          :case_="case_"
          :showSteps="showSteps"
        />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import Applicant from "./Applicant.vue";
import ApplicantSelector from "./ApplicantSelector.vue";
import CaseTable from "./CaseTable.vue";
import Client from "./Client.vue";
import Process from "./Process.vue";
import ProviderContact from "./ProviderContact.vue";
import {
  CaseSerializer,
  ApplicantSerializer,
} from "../autogenerated-interfaces";
import { applicantIsNull, processIsNull } from "../factories";

export default Vue.extend({
  props: {
    case_: Object as PropType<CaseSerializer>,
    showClient: { type: Boolean, default: true },
    showSteps: { type: Boolean, default: true },
  },

  components: {
    Applicant,
    ApplicantSelector,
    CaseTable,
    Client,
    Process,
    ProviderContact,
  },

  data() {
    return {
      applicant: null as ApplicantSerializer | null,
    };
  },

  computed: {
    haveApplicant(): boolean {
      return !applicantIsNull(this.case_.applicant);
    },

    haveProcess(): boolean {
      return !processIsNull(this.case_.process);
    },
  },

  methods: {
    handleSelectApplicant(applicant: ApplicantSerializer) {
      this.$emit("select:applicant", applicant);
    },
  },
});
</script>

