<template>
  <!-- class="section" on the following div makes the table rows vertically aligned -->
  <div>
    <b-tabs>
      <b-tab-item label="Table">
        <b-table
          ref="table"
          :data="rows"
          :selected.sync="selected"
          focusable
          hoverable
          paginated
          @dblclick="navigateToRowDetailView"
          :per-page="10"
        >
          <b-table-column label="Applicant" v-slot="props">
            <applicant :applicant="props.row.applicant"></applicant>
          </b-table-column>

          <b-table-column label="Route" v-slot="props">
            <process :case_="props.row" :showSteps="false"> </process>
          </b-table-column>

          <b-table-column label="Provider" v-slot="props">
            <provider
              v-for="provider in getProviders(props.row)"
              :key="provider.uuid"
              :provider="provider"
              :showName="false"
            >
            </provider>
          </b-table-column>
        </b-table>
      </b-tab-item>

      <b-tab-item label="Selected">
        <case v-if="isGenuineCaseObject(selected)" :case_="selected"></case>
      </b-tab-item>
    </b-tabs>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import BTable from "buefy/src/components/table";
type BTableInstance = InstanceType<typeof BTable>;

import { Role } from "../role";
import {
  CaseSerializer,
  ProviderSerializer,
} from "../autogenerated-interfaces";
import Applicant from "../components/Applicant.vue";
import Case from "../components/Case.vue";
import Process from "../components/Process.vue";
import Provider from "../components/Provider.vue";
import { processIsNull } from "../factories";
import http from "../http";

export default Vue.extend({
  props: { role: String as PropType<Role> },
  components: { Applicant, Case, Process, Provider },
  data() {
    return {
      rows: [] as CaseSerializer[],
      selected: {},
      processIsNull,
      Role,
    };
  },

  async created(): Promise<void> {
    this.fetchCaseList();
  },

  mounted() {
    this.$el.querySelector("table")?.addEventListener("keydown", (event) => {
      if (event.code === "Enter") {
        let table = this.$refs.table as BTableInstance;
        if (table.selected) {
          this.navigateToRowDetailView(table.selected);
        }
      }
    });
  },

  methods: {
    async fetchCaseList(): Promise<void> {
      switch (this.role) {
        case Role.ClientContact:
          var url = "/api/client-contact/list-cases/";
          break;
        case Role.ProviderContact:
          var url = "/api/provider-contact/list-cases/";
          break;
        case Role.Invalid:
          return;
      }
      this.rows = (await http.fetchDataOrNull(url)) || [];
    },

    getProviders(case_: CaseSerializer): ProviderSerializer[] {
      const providers = [];
      const seen = new Set<string>();
      for (let step of case_.steps) {
        if (!step.active_contract) {
          continue;
        }
        let provider = step.active_contract.provider_contact.provider;
        if (provider.uuid && !seen.has(provider.uuid)) {
          providers.push(provider);
          seen.add(provider.uuid);
        }
      }
      return providers.sort((p1, p2) => (p1.name <= p2.name ? 0 : 1));
    },

    navigateToRowDetailView(row: CaseSerializer): void {
      this.$router.push(`/portal/case/${row.uuid}`);
    },

    // TODO: The 'selected' feature of buefy table seems to be being triggered
    // with an empty/non-genuine Case object.
    isGenuineCaseObject(case_: CaseSerializer): boolean {
      return !!case_.applicant;
    },
  },
});
</script>
