<template>
  <vue-file-agent
    :uploadUrl="uploadUrl"
    :uploadHeaders="uploadHeaders"
    :multiple="true"
    v-model="fileRecords"
    @upload:error="handleFileUploadError"
  >
  </vue-file-agent>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import VueFileAgent from "vue-file-agent";
import "vue-file-agent/dist/vue-file-agent.css";
Vue.use(VueFileAgent);
import { VueFileAgentFileRecord } from "../vue-file-agent";
import Cookies from "js-cookie";

import { CaseStepSerializer } from "../autogenerated-interfaces";
import { getRole } from "../role";

export default Vue.extend({
  props: { step: Object as PropType<CaseStepSerializer> },

  data() {
    var uploadUrl = `/api/${getRole()}/case-step/upload-files/${
      this.step.uuid
    }`;
    // TODO: clean way to disable UI Dev mode
    const isUiDevMode = !!process.env.VUE_APP_SERVER_URL;
    if (isUiDevMode) {
      uploadUrl = require("../dev-mode").devModeUrl(
        `${process.env.VUE_APP_SERVER_URL}${uploadUrl}`
      );
    }
    return {
      showDetail: false,
      uploadUrl,
      uploadHeaders: { "X-CSRFToken": Cookies.get("csrftoken") },
      fileRecords: this.step.stored_files.map(
        (f) => new VueFileAgentFileRecord(f)
      ),
    };
  },

  methods: {
    handleFileUploadError(error: Error): void {
      alert(`File upload error: ${error}`);
    },
  },
});
</script>
