<template>
  <!-- A CaseList is a wrapper around a CaseTable component, adding e.g. tabs, and
methods to fetch data. -->
  <!-- class="section" on the following div makes the table rows vertically aligned -->
  <div>
    <b-tabs v-model="activeTab">
      <b-tab-item label="All">
        <case-table
          :rows="rows"
          :selected.sync="selected"
          :focusable="true"
          @dblclick="navigateToRowDetailView"
          :columnSpec="{ provider: { visible: true } }"
          :paginated="true"
        />
      </b-tab-item>

      <b-tab-item label="Selected">
        <case v-if="isGenuineCaseObject(selected)" :case_="selected"></case>
      </b-tab-item>
    </b-tabs>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { Role } from "../role";
import { CaseSerializer } from "../autogenerated-interfaces";
import Case from "../components/Case.vue";
import { processIsNull } from "../factories";
import http from "../http";
import CaseTable from "./CaseTable.vue";
import eventBus from "../event-bus";

export default Vue.extend({
  props: { role: String as PropType<Role> },
  components: { Case, CaseTable },
  data() {
    return {
      activeTab: 0,
      rows: [] as CaseSerializer[],
      selected: {} as CaseSerializer,
      processIsNull,
      Role,
      routeName: this.$route.name,
    };
  },

  async created(): Promise<void> {
    this.fetchCaseList();
  },

  mounted() {
    document.addEventListener("keydown", (event) => {
      if (event.code === "ArrowRight" || event.code === "Enter") {
        eventBus.$emit(
          "update:route-name-override",
          `Case ${this.selected.id || ""}`
        );
        this.activeTab = 1;
      } else if (event.code === "ArrowLeft") {
        this.activeTab = 0;
        eventBus.$emit("update:route-name-override", null);
        this.$nextTick(() => this.$el.querySelector("table")?.focus());
      }
    });
  },

  methods: {
    async fetchCaseList(): Promise<void> {
      switch (this.role) {
        case Role.ClientContact:
          var url = "/api/client-contact/list-cases/";
          break;
        case Role.ProviderContact:
          url = "/api/provider-contact/list-cases/";
          break;
        case Role.Invalid:
          return;
      }
      this.rows = (await http.fetchDataOrNull(url)) || [];
    },

    navigateToRowDetailView(row: CaseSerializer): void {
      this.$router.push(`/portal/case/${row.uuid}`);
    },

    // TODO: The 'selected' feature of buefy table is being triggered with an
    // empty Case object.
    isGenuineCaseObject(case_: CaseSerializer): boolean {
      return !!case_.applicant;
    },
  },
});
</script>
