<template>
  <div :id="dropzoneElementId"></div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import Dropzone from "dropzone";
import Cookies from "js-cookie";

import { CaseStepSerializer } from "../autogenerated-interfaces";
import { getRole } from "../role";

export default Vue.extend({
  props: { step: Object as PropType<CaseStepSerializer> },

  data() {
    var url = `/api/${getRole()}/case-step-upload-files/${this.step.uuid}/`;
    // TODO: clean way to disable UI Dev mode
    const isUiDevMode = true;
    if (isUiDevMode) {
      url = require("../dev-mode").devModeUrl(
        `${process.env.VUE_APP_SERVER_URL}${url}`
      );
    }
    const headers: { [key: string]: string } = {};
    const csrfToken = Cookies.get("csrftoken");
    if (csrfToken) {
      headers["X-CSRFToken"] = csrfToken;
    }
    return {
      dropzoneElementId: `dropzone-${this.step.uuid}`,
      dropzoneOptions: {
        url,
        headers,
      },
    };
  },

  mounted() {
    const existingFiles = this.step.stored_files;
    Dropzone.options.myDropzone = {
      init: function () {
        for (let file of existingFiles) {
          this.displayExistingFile(file, "");
        }
      },
    };
    new Dropzone(`#${this.dropzoneElementId}`, this.dropzoneOptions);
  },
});
</script>
