<template>
  <vue-file-agent
    :uploadUrl="uploadUrl"
    :uploadHeaders="uploadHeaders"
    :multiple="true"
    v-model="fileRecords"
    @upload:error="handleFileUploadError"
  >
  </vue-file-agent>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import VueFileAgent from "vue-file-agent";
import "vue-file-agent/dist/vue-file-agent.css";
Vue.use(VueFileAgent);

import { CaseStepSerializer } from "../autogenerated-interfaces";
import { VueFileAgentFileRecord } from "../vue-file-agent";
import Cookies from "js-cookie";
import { devModeUrl } from "../dev-mode";

export default Vue.extend({
  props: { step: Object as PropType<CaseStepSerializer> },

  data() {
    return {
      showDetail: false,
      uploadUrl: devModeUrl(
        `${process.env.VUE_APP_SERVER_URL}/api/case-step/${this.step.uuid}/upload-files/`
      ),
      uploadHeaders: { "X-CSRFToken": Cookies.get("csrftoken") },
      fileRecords: this.step.stored_files.map(
        (f) => new VueFileAgentFileRecord(f)
      ),
    };
  },

  methods: {
    handleFileUploadError(error: Error): void {
      alert(`File upload error: ${error}`);
    },
  },
});
</script>
