<template>
  <provider-contact-selector
    v-if="canChangeProviderContact"
    placeholder="Select Provider"
    :process="process"
    :giveAppearanceOfSelectingProvider="true"
    :current="
      caseStep.active_contract && caseStep.active_contract.provider_contact
    "
    :initialProviderContacts="providerContacts"
    @change:provider-contact="handleChangeProviderContact"
  />
  <provider
    v-else-if="
      caseStep.active_contract && caseStep.active_contract.provider_contact
    "
    :provider="caseStep.active_contract.provider_contact.provider"
    :showName="false"
  />
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import {
  CaseStepSerializer,
  ProcessSerializer,
  ProviderContactSerializer,
} from "../autogenerated-interfaces";
import Provider from "./Provider.vue";
import ProviderContactSelector from "./ProviderContactSelector.vue";
import { NullCaseStepContract } from "@/factories";
import { isClientContact } from "../role";

export default Vue.extend({
  props: {
    caseStep: Object as PropType<CaseStepSerializer>,
    process: Object as PropType<ProcessSerializer>,
    providerContacts: Array as PropType<ProviderContactSerializer[]>,
  },
  components: {
    Provider,
    ProviderContactSelector,
  },

  computed: {
    canChangeProviderContact(): boolean {
      if (!isClientContact()) {
        return false;
      }
      for (let action of this.caseStep.actions) {
        if (action.name == "client_contact_earmark_case_step") {
          return true;
        }
      }
      return false;
    },
  },

  methods: {
    handleChangeProviderContact(providerContact: ProviderContactSerializer) {
      const caseStep = Object.assign({}, this.caseStep);
      if (!caseStep.active_contract) {
        caseStep.active_contract = NullCaseStepContract();
      }
      caseStep.active_contract.provider_contact = providerContact;
      this.$emit("update:case-step", caseStep);
    },
  },
});
</script>

<style scoped>
</style>