<template>
  <div>
    <div>
      <div class="card">
        <header class="card-header" @click="showDetail = !showDetail">
          <p class="card-header-title">
            {{ step.sequence_number }}. {{ step.process_step.service.name }}
          </p>
        </header>
        <div v-if="showDetail" class="card-content">
          <div class="content">
            [Additional information for step {{ step.sequence_number }}]
          </div>
        </div>
        <footer v-if="showDetail" class="card-footer">
          <a href="#" class="card-footer-item">
            <vue-file-agent
              :uploadUrl="uploadUrl"
              :uploadHeaders="uploadHeaders"
              :multiple="true"
              v-model="fileRecords"
            ></vue-file-agent>
          </a>
        </footer>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import VueFileAgent from "vue-file-agent";
import "vue-file-agent/dist/vue-file-agent.css";
Vue.use(VueFileAgent);
import Cookies from "js-cookie";

import { CaseStepSerializer } from "../autogenerated-interfaces";
import { VueFileAgentFileRecord } from "../vue-file-agent";

export default Vue.extend({
  props: { step: Object as PropType<CaseStepSerializer> },

  data() {
    return {
      showDetail: false,
      uploadUrl: `${process.env.VUE_APP_SERVER_URL}/api/case-step/${this.step.id}/upload-files/`,
      uploadHeaders: { "X-CSRFToken": Cookies.get("csrftoken") },
      fileRecords: this.step.stored_files.map(
        (f) => new VueFileAgentFileRecord(f)
      ),
    };
  },
});
</script>

<style scoped>
</style>