// A table that can be used to display a listg of cases, or a single case as a
// header for a case detail view.
<template>
  <b-table
    ref="table"
    :data="rows"
    :selected.sync="selected"
    :paginated="paginated"
    focusable
    hoverable
    @dblclick="(row) => $emit('dblclick', row)"
    :per-page="10"
  >
    <b-table-column label="Applicant" v-slot="props">
      <applicant :applicant="props.row.applicant"></applicant>
    </b-table-column>

    <b-table-column label="Route" v-slot="props">
      <process :case_="props.row" :showSteps="false"> </process>
    </b-table-column>

    <b-table-column v-if="showProviders" label="Provider" v-slot="props">
      <provider
        v-for="provider in getProviders(props.row)"
        :key="provider.uuid"
        :provider="provider"
        :showName="false"
      >
      </provider>
    </b-table-column>
  </b-table>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { CaseSerializer, ProviderSerializer } from "@/autogenerated-interfaces";
import Applicant from "../components/Applicant.vue";
import Process from "../components/Process.vue";
import Provider from "../components/Provider.vue";

export default Vue.extend({
  props: {
    rows: Array as PropType<CaseSerializer[]>,
    paginated: Boolean,
    showProviders: Boolean,
  },
  components: { Applicant, Process, Provider },

  data() {
    return {
      selected: {},
    };
  },

  methods: {
    getProviders(case_: CaseSerializer): ProviderSerializer[] {
      const providers = [];
      const seen = new Set<string>();
      for (let step of case_.steps) {
        if (!step.active_contract) {
          continue;
        }
        let provider = step.active_contract.provider_contact.provider;
        if (provider.uuid && !seen.has(provider.uuid)) {
          providers.push(provider);
          seen.add(provider.uuid);
        }
      }
      return providers.sort((p1, p2) => (p1.name <= p2.name ? 0 : 1));
    },
  },
});
</script>
