<template>
  <div>
    <div>
      <div class="card">
        <header class="card-header" @click="showDetail = !showDetail">
          <p class="card-header-title title is-size-6">
            {{ step.sequence_number }}. {{ step.process_step.service.name }}
          </p>
          <provider-contact
            v-if="step.provider_contact"
            :provider_contact="step.provider_contact"
            class="mr-3"
          >
          </provider-contact>
          <div v-else>[No provider contact assigned]</div>
        </header>
        <div v-if="showDetail" class="card-content">
          <a href="#" class="card-footer-item">
            <vue-file-agent
              :uploadUrl="uploadUrl"
              :uploadHeaders="uploadHeaders"
              :multiple="true"
              v-model="fileRecords"
            ></vue-file-agent>
          </a>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import VueFileAgent from "vue-file-agent";
import "vue-file-agent/dist/vue-file-agent.css";
Vue.use(VueFileAgent);
import Cookies from "js-cookie";

import { CaseStepSerializer } from "../autogenerated-interfaces";
import ProviderContact from "../components/ProviderContact.vue";
import { VueFileAgentFileRecord } from "../vue-file-agent";
import { devModeUrl } from "../dev-mode";

export default Vue.extend({
  components: { ProviderContact },
  props: { step: Object as PropType<CaseStepSerializer> },

  data() {
    return {
      showDetail: false,
      uploadUrl: devModeUrl(
        `${process.env.VUE_APP_SERVER_URL}/api/case-step/${this.step.id}/upload-files/`
      ),
      uploadHeaders: { "X-CSRFToken": Cookies.get("csrftoken") },
      fileRecords: this.step.stored_files.map(
        (f) => new VueFileAgentFileRecord(f)
      ),
    };
  },
});
</script>

<style scoped>
</style>