<template>
  <!-- class="section" on the following div makes the table rows vertically aligned -->
  <div>
    <b-tabs>
      <b-tab-item label="Table">
        <b-table
          ref="table"
          :data="rows"
          :selected.sync="selected"
          focusable
          hoverable
          paginated
          @dblclick="navigateToRowDetailView"
          :per-page="10"
        >
          <b-table-column label="Provider" v-slot="props">
            <provider :provider="props.row.provider"> </provider>
          </b-table-column>

          <b-table-column label="Primary" v-slot="props">
            {{ props.row.preferred }}
          </b-table-column>
        </b-table>
      </b-tab-item>

      <b-tab-item label="Selected">
        <client-provider-relationship
          v-if="selected && selected.logo_url"
          :relationship="selected"
        >
        </client-provider-relationship>
      </b-tab-item>
    </b-tabs>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import BTable from "buefy/src/components/table";
type BTableInstance = InstanceType<typeof BTable>;

import { ClientProviderRelationshipSerializer } from "../autogenerated-interfaces";
import Provider from "./Provider.vue";

export default Vue.extend({
  components: { Provider },
  data() {
    return {
      rows: [] as ClientProviderRelationshipSerializer[],
      selected: {},
    };
  },

  async created(): Promise<void> {
    this.fetchClientProviderRelationshipList();
  },

  mounted() {
    this.$el.querySelector("table")?.addEventListener("keydown", (event) => {
      if (event.code === "Enter") {
        let table = this.$refs.table as BTableInstance;
        if (table.selected) {
          this.navigateToRowDetailView(table.selected);
        }
      }
    });
  },

  methods: {
    async fetchClientProviderRelationshipList(): Promise<void> {
      const url = `${process.env.VUE_APP_SERVER_URL}/api/client-contact/list-provider-relationships/`;
      const resp = await fetch(url);
      this.rows = await resp.json();
    },

    navigateToRowDetailView(row: ClientProviderRelationshipSerializer): void {
      this.$router.push(`/portal/provider/${row.id}`);
    },
  },
});
</script>
