<template>
  <div class="media">
    <div class="media-left">
      <img :src="relationship.provider.logo_url" width="128px" />
    </div>
    <div class="media-content">
      <p class="title is-size-6">
        {{ relationship.provider.name }}
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { ClientProviderRelationshipSerializer } from "@/autogenerated-interfaces";
import Vue, { PropType } from "vue";

export default Vue.extend({
  props: {
    relationship: Object as PropType<ClientProviderRelationshipSerializer>,
  },
});
</script>

<style scoped>
a,
a:hover {
  color: currentColor;
}
</style>