<template>
  <div class="media">
    <div class="media-left">
      <img :src="client.logo_url" width="88px" />
    </div>
    <div v-if="showName" class="media-content">
      <p class="title is-size-6">
        {{ client.name }}
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { Client as IClient } from "@/autogenerated-interfaces/client";
import Vue, { PropType } from "vue";

export default Vue.extend({
  props: {
    client: Object as PropType<IClient>,
    showName: {
      type: Boolean,
      default: true,
    },
  },
});
</script>

<style scoped>
a,
a:hover {
  color: currentColor;
}
</style>
