<template>
  <div v-if="showName">
    <img v-bind="imageProps" />
    <span> {{ country.name }}</span>
  </div>
  <b-tooltip v-else :label="country.name" type="is-info is-light">
    <img v-bind="imageProps" />
  </b-tooltip>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { CountrySerializer } from "@/autogenerated-interfaces";
import { makeFlagImgProps, ImgProps } from "../flags";

export default Vue.extend({
  props: {
    country: Object as PropType<CountrySerializer>,
    editable: Boolean,
    showName: {
      type: Boolean,
      default: false,
    },
  },

  computed: {
    imageProps(): ImgProps {
      return makeFlagImgProps(this.country);
    },
  },
});
</script>

<style scoped></style>
