<template>
  <div class="field has-addons" style="width: 100%">
    <p class="control" style="width: 100%">
      <b-field :label="label">
        <b-autocomplete
          ref="autocomplete"
          v-model="input"
          field="name"
          :data="filteredCandidates"
          @select="(country) => $emit('change:country', country)"
          :openOnFocus="true"
          dropdown-position="bottom"
          max-height="100vh"
        >
          <template slot-scope="props">
            {{ props.option.displayName }}
          </template>
        </b-autocomplete>
      </b-field>
    </p>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { CountrySerializer } from "../autogenerated-interfaces";
import { inputMatchesString } from "../utils";
import { dismissMobileKeyboardOnDropdownScroll } from "../componentUtils";

export default Vue.extend({
  props: {
    candidateCountries: Array as PropType<CountrySerializer[]>,
    label: String,
  },

  data() {
    return {
      input: "",
    };
  },

  mounted() {
    dismissMobileKeyboardOnDropdownScroll(this, "autocomplete");
  },

  computed: {
    filteredCandidates(): CountrySerializer[] {
      return this.candidateCountries
        .filter((country) => inputMatchesString(this.input, country.name))
        .map((country) => {
          return Object.assign(country, {
            displayName: `${country.unicode_flag} ${country.name}`,
          });
        });
    },
  },
});
</script>
