<template>
  <b-tooltip :label="country.name">
    <figure class="image is-4x3">
      <img v-bind="imageProps" />
    </figure>
  </b-tooltip>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { CountrySerializer } from "@/autogenerated-interfaces";
import { makeFlagImgProps, ImgProps } from "../flags";

export default Vue.extend({
  props: { country: Object as PropType<CountrySerializer> },

  computed: {
    imageProps(): ImgProps {
      return makeFlagImgProps(this.country);
    },
  },
});
</script>

<style scoped>
</style>