<template>
  <b-tooltip :label="country.name" type="is-info is-light">
    <img v-bind="imageProps" />
  </b-tooltip>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { CountrySerializer } from "@/autogenerated-interfaces";
import { makeFlagImgProps, ImgProps } from "../flags";

export default Vue.extend({
  props: { country: Object as PropType<CountrySerializer> },

  computed: {
    imageProps(): ImgProps {
      return makeFlagImgProps(this.country);
    },
  },
});
</script>

<style scoped>
</style>