<template>
  <provider-contact-selector
    v-if="providerEditable && state === State.Selecting"
    ref="providerContactSelector"
    :candidateProviderContacts="candidateProviderContacts"
    :giveAppearanceOfSelectingProvider="true"
    @select:provider-contact="handleUpdateProviderContact"
    class="provider-contact-selector"
  />
  <div v-else @click="handleClick">
    <provider
      v-for="provider in providers"
      :key="provider.uuid"
      :provider="provider"
      :providerEditable="providerEditable"
      :showName="false"
    />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { BAutocomplete } from "buefy/src/components/autocomplete";

import Provider from "./Provider.vue";
import ProviderContactSelector from "./ProviderContactSelector.vue";
import {
  ProviderSerializer,
  ProviderContactSerializer,
  ProcessSerializer,
} from "../autogenerated-interfaces";
import { isClientContact } from "@/role";
import { processIsNull } from "@/factories";
import http from "../http";
import eventBus from "@/event-bus";

type ProviderContactSelectorType = InstanceType<typeof ProviderContactSelector>;
type BAutocompleteType = InstanceType<typeof BAutocomplete>;

enum State {
  Displaying,
  Selecting,
}

export default Vue.extend({
  props: {
    providers: Array as PropType<ProviderSerializer[]>,
    providerEditable: Boolean,
    process: Object as PropType<ProcessSerializer>,
  },

  components: {
    Provider,
    ProviderContactSelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
      candidateProviderContacts: [] as ProviderContactSerializer[],
    };
  },

  created() {
    if (!processIsNull(this.process)) {
      this.fetchProviderContacts(this.process);
    }
    if (this.hasProvider) {
      this.state = State.Displaying;
    }
  },

  computed: {
    hasProvider(): boolean {
      return Boolean(this.providers[0]);
    },

    // TODO: make this a method
    canUpdateProvider(): boolean {
      return isClientContact();
    },
  },

  watch: {
    process: function (value: ProcessSerializer): void {
      this.fetchProviderContacts(value);
    },
  },

  methods: {
    async fetchProviderContacts(process_: ProcessSerializer) {
      if (!process_.uuid) {
        // TODO: why?
        return;
      }
      const url = `/api/client-contact/list-primary-provider-contacts/?process_uuid=${process_.uuid}`;
      this.candidateProviderContacts = (await http.fetchDataOrNull(url)) || [];
    },
    handleUpdateProviderContact(providerContact: ProviderContactSerializer) {
      if (!providerContact) {
        // FIXME: why
        console.log(
          "ERROR: providerContact is",
          JSON.stringify(providerContact)
        );
        return;
      }
      eventBus.$emit("update:provider-contact", providerContact);
      this.state = State.Displaying;
    },

    handleClick() {
      if (this.state === State.Displaying) {
        if (this.canUpdateProvider) {
          this.state = State.Selecting;
          this.$nextTick(() => {
            const providerContactSelector = this.$refs
              .providerContactSelector as ProviderContactSelectorType;
            const autocomplete: BAutocompleteType =
              providerContactSelector.$refs.autocomplete;
            const input: HTMLElement = autocomplete.$refs.input.$refs.input;
            input.focus();
          });
        }
      }
    },
  },
});
</script>
