<template>
  <applicant-selector
    ref="applicantSelector"
    v-if="applicantEditable && state === State.Selecting"
    :candidateApplicants="candidateApplicants"
    @change:applicant="handleUpdateApplicant"
    class="applicant-selector"
  />
  <div v-else @click="handleClick">
    <applicant :applicant="applicant" :applicantEditable="applicantEditable" />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { BAutocomplete } from "buefy/src/components/autocomplete";

import Applicant from "./Applicant.vue";
import ApplicantSelector from "./ApplicantSelector.vue";
import { ApplicantSerializer } from "../autogenerated-interfaces";
import { applicantIsNull } from "@/factories";
import { isClientContact } from "@/role";
import eventBus from "@/event-bus";
import http from "../http";

type ApplicantSelectorType = InstanceType<typeof ApplicantSelector>;
type BAutocompleteType = InstanceType<typeof BAutocomplete>;

enum State {
  Displaying,
  Selecting,
}

export default Vue.extend({
  props: {
    applicant: Object as PropType<ApplicantSerializer>,
    applicantEditable: Boolean,
  },

  components: {
    Applicant,
    ApplicantSelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
      candidateApplicants: [] as ApplicantSerializer[],
    };
  },

  async created() {
    if (this.hasApplicant) {
      this.state = State.Displaying;
    }
    this.candidateApplicants =
      (await http.fetchDataOrNull("/api/client-contact/applicants/")) || [];
  },

  computed: {
    hasApplicant(): boolean {
      return !applicantIsNull(this.applicant);
    },

    // TODO: make this a method
    canUpdateApplicant(): boolean {
      return isClientContact();
    },
  },

  methods: {
    handleUpdateApplicant(applicant: ApplicantSerializer) {
      if (!applicant) {
        // FIXME: why
        console.log("ERROR: applicant is", JSON.stringify(applicant));
        return;
      }
      eventBus.$emit("update:applicant", applicant);
      this.state = State.Displaying;
    },

    handleClick() {
      if (this.state === State.Displaying) {
        if (this.canUpdateApplicant) {
          this.state = State.Selecting;
          this.$nextTick(() => {
            const applicantSelector = this.$refs
              .applicantSelector as ApplicantSelectorType;
            const autocomplete: BAutocompleteType =
              applicantSelector.$refs.autocomplete;
            const input: HTMLElement = autocomplete.$refs.input.$refs.input;
            input.focus();
          });
        }
      }
    },
  },
});
</script>

<style scoped>
</style>