<template>
  <applicant-selector
    v-if="canUpdate && state === State.Selecting"
    ref="selector"
    :candidateApplicants="candidateApplicants"
    @select:applicant="handleSelect"
    @blur="editableComponentProxy.handleSelectorBlur()"
    class="applicant-selector"
  />
  <div v-else @click="editableComponentProxy.handleDisplayerClick()">
    <applicant :applicant="applicant" :applicantEditable="applicantEditable" />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import Applicant from "./Applicant.vue";
import ApplicantSelector from "./ApplicantSelector.vue";
import { EditableComponentProxy, State } from "../editable-component";
import { ApplicantSerializer } from "../autogenerated-interfaces";
import { applicantIsNull } from "@/factories";
import { isClientContact } from "@/role";
import eventBus from "@/event-bus";
import http from "../http";

export default Vue.extend({
  props: {
    applicant: Object as PropType<ApplicantSerializer>,
    applicantEditable: Boolean,
  },

  components: {
    Applicant,
    ApplicantSelector,
  },

  data() {
    return {
      state: State.Selecting,
      candidateApplicants: [] as ApplicantSerializer[],
      State,
    };
  },

  async created() {
    this.state = this.hasDisplayable ? State.Displaying : State.Selecting;
    this.candidateApplicants =
      (await http.fetchDataOrNull("/api/client-contact/applicants/")) || [];
  },

  computed: {
    editableComponentProxy(): EditableComponentProxy {
      return new EditableComponentProxy(this);
    },

    hasDisplayable(): boolean {
      return !applicantIsNull(this.applicant);
    },

    // TODO: make this a method
    canUpdate(): boolean {
      return isClientContact() && this.applicantEditable;
    },
  },

  methods: {
    handleSelect(applicant: ApplicantSerializer) {
      if (!applicant) {
        // FIXME: why
        console.log("ERROR: applicant is", JSON.stringify(applicant));
        return;
      }
      eventBus.$emit("update:applicant", applicant);
      // We've just selected a value, so show the rich display of the value
      // instead of the value in the selection widget.
      this.state = State.Displaying;
    },
  },
});
</script>
