<template>
  <route-selector
    ref="routeSelector"
    v-if="routeEditable && state === State.Selecting"
    :candidateProcesses="candidateProcesses"
    @change:process="handleUpdateProcess"
    class="route-selector"
  />
  <div v-else @click="handleClick">
    <route :route="route" :routeEditable="routeEditable" />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { BAutocomplete } from "buefy/src/components/autocomplete";

import Route from "./Route.vue";
import RouteSelector from "./RouteSelector.vue";
import {
  ProcessSerializer,
  RouteSerializer,
} from "../autogenerated-interfaces";
import { routeIsNull } from "@/factories";
import { isClientContact } from "@/role";
import eventBus from "@/event-bus";

type RouteSelectorType = InstanceType<typeof RouteSelector>;
type BAutocompleteType = InstanceType<typeof BAutocomplete>;

enum State {
  Displaying,
  Selecting,
}

export default Vue.extend({
  props: {
    route: Object as PropType<RouteSerializer>,
    routeEditable: Boolean,
  },

  components: {
    Route,
    RouteSelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
      candidateProcesses: [] as ProcessSerializer[],
    };
  },

  created() {
    if (this.hasRoute) {
      this.state = State.Displaying;
    }
    eventBus.$on(
      "update:candidate-processes",
      (processes: ProcessSerializer[]) => (this.candidateProcesses = processes)
    );
  },

  computed: {
    hasRoute(): boolean {
      return !routeIsNull(this.route);
    },

    // TODO: make this a method
    canUpdateRoute(): boolean {
      return isClientContact();
    },
  },

  methods: {
    handleUpdateProcess(process: ProcessSerializer) {
      if (!process) {
        // FIXME: why
        console.log("ERROR: process is", JSON.stringify(process));
        return;
      }
      eventBus.$emit("update:process", process);
      this.state = State.Displaying;
    },

    handleClick() {
      if (this.state === State.Displaying) {
        if (this.canUpdateRoute) {
          this.state = State.Selecting;
          this.$nextTick(() => {
            const routeSelector = this.$refs.routeSelector as RouteSelectorType;
            const autocomplete: BAutocompleteType =
              routeSelector.$refs.autocomplete;
            const input: HTMLElement = autocomplete.$refs.input.$refs.input;
            input.focus();
          });
        }
      }
    },
  },
});
</script>
