<template>
  <fieldset
    v-if="canUpdate && state === State.Selecting"
    :disabled="editingSpec.disabled"
  >
    <provider-contact-selector
      ref="selector"
      placeholder="Select Provider"
      :giveAppearanceOfSelectingProvider="true"
      :candidateProviderContacts="candidateProviderContacts"
      @select:provider-contact="handleSelect"
      @blur="editableComponentProxy.handleSelectorBlur()"
    />
  </fieldset>
  <div v-else @click="editableComponentProxy.handleDisplayerClick()">
    <provider
      v-if="caseStep.active_contract"
      :provider="caseStep.active_contract.provider_contact.provider"
      :providerEditable="editingSpec.editable"
      :showName="false"
    />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { ProviderContact as IProviderContact } from "../autogenerated-interfaces/app";
import { CaseStep as ICaseStep } from "../autogenerated-interfaces/client";
import { ProcessRuleSet as IProcess } from "../autogenerated-interfaces/immigration";
import Provider from "./Provider.vue";
import ProviderContactSelector from "./ProviderContactSelector.vue";
import {
  EditableComponentProxy,
  EditingSpec,
  State,
} from "../editable-component";
import { NullCaseStepContract, processIsNull } from "@/factories";
import { isClientContact } from "../role";
import http from "@/http";

export default Vue.extend({
  props: {
    caseStep: Object as PropType<ICaseStep>,
    editingSpec: Object as PropType<EditingSpec>,
    process: Object as PropType<IProcess>,
  },

  components: {
    Provider,
    ProviderContactSelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
      candidateProviderContacts: [] as IProviderContact[],
    };
  },

  mounted() {
    // HACK: A retract event updates the case step with a null provider value.
    // We want this to put the editable component into Selecting mode, but
    // currently nothing effects that transition. So for now we are forcing a
    // rerender of the component in response to the event; if the state gets set
    // correctly on component recreation then this will have the desired effect.
    // That seems slighly more defensible than setting the state explicitly here
    // when I'm not sure what the right implementation is (i.e. where/when that
    // state should be getting set).
    this.state = this.hasDisplayable ? State.Displaying : State.Selecting;
    if (this.canUpdate && !processIsNull(this.process)) {
      this.fetchProviderContacts(this.process);
    }
  },

  computed: {
    editableComponentProxy(): EditableComponentProxy {
      return new EditableComponentProxy(this);
    },

    providerEditable(): boolean {
      return isClientContact() && this.editingSpec.editable;
    },

    hasDisplayable(): boolean {
      return !!this.caseStep.active_contract?.provider_contact;
    },

    canUpdate(): boolean {
      if (!isClientContact()) {
        return false;
      }
      if (this.caseStep.state?.name == "FREE") {
        return true;
      }
      if (!this.editingSpec.editable) {
        return false;
      }
      for (let action of this.caseStep.actions) {
        if (action.name == "client_contact_earmark_case_step") {
          return true;
        }
      }
      return false;
    },
  },

  watch: {
    canUpdate: function (newValue: boolean): void {
      if (newValue && this.process) {
        this.fetchProviderContacts(this.process);
      }
    },

    process: function (newValue: IProcess): void {
      if (this.canUpdate) {
        this.fetchProviderContacts(newValue);
      }
    },

    hasDisplayable(newValue: boolean): void {
      // HACK
      if (!newValue) {
        this.state = State.Selecting;
      }
    },
  },

  methods: {
    // TODO: duplicated in EditableProvider.vue
    async fetchProviderContacts(process_: IProcess) {
      if (!process_.uuid) {
        // TODO: why?
        console.error(
          "CaseSteps.fetchProviderContacts: process_.uuid is null:",
          process_
        );
        return;
      }
      const url = `/api/client-contact/list-primary-provider-contacts/?process_uuid=${process_.uuid}`;
      this.candidateProviderContacts = (await http.fetchDataOrNull(url)) || [];
    },

    handleSelect(providerContact: IProviderContact) {
      const caseStep = Object.assign({}, this.caseStep);
      if (!caseStep.active_contract) {
        caseStep.active_contract = NullCaseStepContract();
      }
      caseStep.active_contract.provider_contact = providerContact;
      this.$emit("update:case-step", caseStep);
      this.state = State.Displaying;
    },
  },
});
</script>
