<template>
  <fieldset
    v-if="canUpdate && state === State.Selecting"
    :disabled="editingSpec.disabled"
  >
    <provider-contact-selector
      ref="selector"
      :candidateProviderContacts="candidateProviderContacts"
      :giveAppearanceOfSelectingProvider="true"
      @select:provider-contact="handleSelect"
      @blur="editableComponentProxy.handleSelectorBlur()"
      class="provider-contact-selector"
    />
  </fieldset>
  <div v-else @click="editableComponentProxy.handleDisplayerClick()">
    <provider
      v-for="provider in providers"
      :key="provider.uuid"
      :provider="provider"
      :providerEditable="editingSpec.editable"
      :showName="false"
    />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import Provider from "./Provider.vue";
import ProviderContactSelector from "./ProviderContactSelector.vue";
import {
  EditableComponentProxy,
  EditingSpec,
  State,
} from "../editable-component";
import {
  ProviderSerializer,
  ProviderContactSerializer,
  ProcessSerializer,
  CaseStepSerializer,
} from "../autogenerated-interfaces";
import { isClientContact } from "@/role";
import { processIsNull } from "@/factories";
import http from "../http";
import eventBus from "@/event-bus";

export default Vue.extend({
  props: {
    editingSpec: Object as PropType<EditingSpec>,
    // TODO: `process` and `steps` are not independent: if the steps all belong
    // to the same process then that is the definition of `process`; otherwise,
    // `process` is not defined. So, this component should probably take in
    // `steps` alone, and compute `process`, if it can be computed.
    process: Object as PropType<ProcessSerializer>,
    steps: Array as PropType<CaseStepSerializer[]>,
  },

  components: {
    Provider,
    ProviderContactSelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
      candidateProviderContacts: [] as ProviderContactSerializer[],
    };
  },

  created() {
    this.state = this.hasDisplayable ? State.Displaying : State.Selecting;
    if (this.canUpdate && !processIsNull(this.process)) {
      this.fetchProviderContacts(this.process);
    }
  },

  computed: {
    editableComponentProxy(): EditableComponentProxy {
      return new EditableComponentProxy(this);
    },

    providers(): ProviderSerializer[] {
      const providers = [];
      const seen = new Set<string>();
      for (let step of this.steps) {
        if (!step.active_contract) {
          continue;
        }
        let provider = step.active_contract.provider_contact.provider;
        if (provider.uuid && !seen.has(provider.uuid)) {
          providers.push(provider);
          seen.add(provider.uuid);
        }
      }
      return providers.sort((p1, p2) => (p1.name <= p2.name ? 0 : 1));
    },

    hasDisplayable(): boolean {
      return this.providers.length > 0;
    },

    // TODO: make this a method
    canUpdate(): boolean {
      return isClientContact() && this.editingSpec.editable;
    },
  },

  watch: {
    process: function (value: ProcessSerializer): void {
      if (this.canUpdate) {
        this.fetchProviderContacts(value);
      }
    },
  },

  methods: {
    // TODO: duplicated in CaseSteps.vue
    async fetchProviderContacts(process_: ProcessSerializer) {
      if (!process_.uuid) {
        // TODO: why?
        console.error(
          "CaseSteps.fetchProviderContacts: process_.uuid is null:",
          process_
        );
        return;
      }
      const url = `/api/client-contact/list-primary-provider-contacts/?process_uuid=${process_.uuid}`;
      this.candidateProviderContacts = (await http.fetchDataOrNull(url)) || [];
    },

    handleSelect(providerContact: ProviderContactSerializer) {
      if (!providerContact) {
        // FIXME: why
        console.error(
          "ERROR: providerContact is",
          JSON.stringify(providerContact)
        );
        return;
      }
      eventBus.$emit("update:provider-contact", providerContact);
      this.state = State.Displaying;
    },
  },
});
</script>
