<template>
  <fieldset
    v-if="canUpdate && state === State.Selecting"
    :disabled="editingSpec.disabled"
  >
    <country-selector
      ref="selector"
      :candidateCountries="candidateCountries"
      @select:country="handleSelect"
      @blur="editableComponentProxy.handleSelectorBlur()"
      class="country-selector"
    />
  </fieldset>
  <div v-else @click="editableComponentProxy.handleDisplayerClick()">
    <country
      :country="country"
      :countryEditable="editingSpec.editable"
      :showName="showName"
    />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import Country from "./Country.vue";
import CountrySelector from "./CountrySelector.vue";
import {
  EditableComponentProxy,
  EditingSpec,
  State,
} from "../editable-component";
import { CountrySerializer } from "../autogenerated-interfaces";
import { countryIsNull } from "@/factories";
import { isClientContact } from "@/role";
import eventBus from "@/event-bus";
import http from "../http";

export default Vue.extend({
  props: {
    country: Object as PropType<CountrySerializer>,
    editingSpec: Object as PropType<EditingSpec>,
    disabled: {
      type: Boolean,
      default: false,
    },
    showName: {
      type: Boolean,
      default: false,
    },
  },

  components: {
    Country,
    CountrySelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
      candidateCountries: [] as CountrySerializer[],
    };
  },

  async created() {
    this.state = this.hasDisplayable ? State.Displaying : State.Selecting;
    this.candidateCountries =
      (await http.fetchDataOrNull("/api/countries/")) || [];
  },

  computed: {
    editableComponentProxy(): EditableComponentProxy {
      return new EditableComponentProxy(this);
    },

    hasDisplayable(): boolean {
      return !countryIsNull(this.country);
    },

    // TODO: make this a method
    canUpdate(): boolean {
      return isClientContact() && this.editingSpec.editable;
    },
  },

  methods: {
    handleSelect(country: CountrySerializer) {
      if (!country) {
        // FIXME: why
        console.log("ERROR: country is", JSON.stringify(country));
        return;
      }
      eventBus.$emit("update:country", country);
      this.state = State.Displaying;
    },
  },
});
</script>
