<template>
  <country-selector
    v-if="canUpdateCountry && state === State.Selecting"
    ref="countrySelector"
    :candidateCountries="candidateCountries"
    @select:country="handleSelect"
    @blur="handleSelectorBlur"
    class="country-selector"
  />
  <div v-else @click="handleDisplayerClick">
    <country :country="country" :countryEditable="countryEditable" />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { BAutocomplete } from "buefy/src/components/autocomplete";

import Country from "./Country.vue";
import CountrySelector from "./CountrySelector.vue";
import { CountrySerializer } from "../autogenerated-interfaces";
import { countryIsNull } from "@/factories";
import { isClientContact } from "@/role";
import eventBus from "@/event-bus";
import http from "../http";

type CountrySelectorType = InstanceType<typeof CountrySelector>;
type BAutocompleteType = InstanceType<typeof BAutocomplete>;

enum State {
  Displaying,
  Selecting,
}

export default Vue.extend({
  props: {
    country: Object as PropType<CountrySerializer>,
    countryEditable: Boolean,
  },

  components: {
    Country,
    CountrySelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
      candidateCountries: [] as CountrySerializer[],
    };
  },

  async created() {
    this.state = this.hasCountry ? State.Displaying : State.Selecting;
    this.candidateCountries =
      (await http.fetchDataOrNull("/api/countries/")) || [];
  },

  computed: {
    hasCountry(): boolean {
      return !countryIsNull(this.country);
    },

    // TODO: make this a method
    canUpdateCountry(): boolean {
      return isClientContact() && this.countryEditable;
    },
  },

  methods: {
    handleSelect(country: CountrySerializer) {
      if (!country) {
        // FIXME: why
        console.log("ERROR: country is", JSON.stringify(country));
        return;
      }
      eventBus.$emit("update:country", country);
      this.state = State.Displaying;
    },

    handleDisplayerClick() {
      if (this.canUpdateCountry) {
        this.state = State.Selecting;
        this.$nextTick(() => {
          const countrySelector = this.$refs
            .countrySelector as CountrySelectorType;
          const autocomplete: BAutocompleteType =
            countrySelector.$refs.autocomplete;
          const input: HTMLElement = autocomplete.$refs.input.$refs.input;
          input.focus();
        });
      }
    },

    handleSelectorBlur(): void {
      // Hack: Changing state to Displaying will hide the autocomplete input
      // element. However, we need to give it a chance to emit its `select`
      // event, and it does not do this when it is hidden (at least, on MacOS
      // Chrome). So, we delay the state change to give time for the `select`
      // event to fire. I think that it should be possible to effect this delay
      // using $nextTick, but that didn't work in practice. There is some
      // animation in the buefy autocomplete code that may be relevant.
      setTimeout(() => (this.state = State.Displaying), 101);
    },
  },
});
</script>
