<template>
  <fieldset
    v-if="canUpdate && state === State.Selecting"
    :disabled="editingSpec.disabled"
  >
    <route-selector
      ref="selector"
      :candidateProcesses="candidateProcesses"
      @select:process="handleSelect"
      @blur="editableComponentProxy.handleSelectorBlur()"
      class="route-selector"
    />
  </fieldset>
  <div v-else @click="editableComponentProxy.handleDisplayerClick()">
    <route :route="route" :routeEditable="editingSpec.editable" />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import Route from "./Route.vue";
import RouteSelector from "./RouteSelector.vue";
import {
  EditableComponentProxy,
  EditingSpec,
  State,
} from "../editable-component";
import {
  ProcessSerializer,
  RouteSerializer,
} from "../autogenerated-interfaces";
import { routeIsNull } from "@/factories";
import { isClientContact } from "@/role";
import eventBus from "@/event-bus";

export default Vue.extend({
  props: {
    route: Object as PropType<RouteSerializer>,
    editingSpec: Object as PropType<EditingSpec>,
  },

  components: {
    Route,
    RouteSelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
      candidateProcesses: [] as ProcessSerializer[],
    };
  },

  created() {
    this.state = this.hasDisplayable ? State.Displaying : State.Selecting;
    eventBus.$on(
      "update:candidate-processes",
      (processes: ProcessSerializer[]) => (this.candidateProcesses = processes)
    );
  },

  computed: {
    editableComponentProxy(): EditableComponentProxy {
      return new EditableComponentProxy(this);
    },

    hasDisplayable(): boolean {
      return !routeIsNull(this.route);
    },

    // TODO: make this a method
    canUpdate(): boolean {
      return isClientContact() && this.editingSpec.editable;
    },
  },

  methods: {
    handleSelect(process: ProcessSerializer) {
      if (!process) {
        // FIXME: why
        console.log("ERROR: process is", JSON.stringify(process));
        return;
      }
      eventBus.$emit("update:process", process);
      this.state = State.Displaying;
    },
  },
});
</script>
