<template>
  <provider-contact-selector
    v-if="providerEditable && state === State.Selecting"
    ref="selector"
    placeholder="Select Provider"
    :giveAppearanceOfSelectingProvider="true"
    :candidateProviderContacts="candidateProviderContacts"
    @select:provider-contact="handleSelect"
    @blur="editableComponentProxy.handleSelectorBlur()"
  />
  <div v-else @click="editableComponentProxy.handleDisplayerClick()">
    <provider
      :provider="caseStep.active_contract.provider_contact.provider"
      :providerEditable="providerEditable"
      :showName="false"
    />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import {
  CaseStepSerializer,
  ProviderContactSerializer,
} from "../autogenerated-interfaces";
import Provider from "./Provider.vue";
import ProviderContactSelector from "./ProviderContactSelector.vue";
import { EditableComponentProxy, State } from "../editable-component";
import { NullCaseStepContract } from "@/factories";
import { isClientContact } from "../role";

export default Vue.extend({
  props: {
    caseStep: Object as PropType<CaseStepSerializer>,
    caseStepEditable: Object,
    candidateProviderContacts: Array as PropType<ProviderContactSerializer[]>,
  },

  components: {
    Provider,
    ProviderContactSelector,
  },

  data() {
    return {
      state: State.Selecting,
      State,
    };
  },

  created() {
    this.state = this.hasDisplayable ? State.Displaying : State.Selecting;
  },

  computed: {
    editableComponentProxy(): EditableComponentProxy {
      return new EditableComponentProxy(this);
    },

    providerEditable(): boolean {
      return isClientContact() && this.caseStepEditable.provider;
    },

    hasDisplayable(): boolean {
      return !!this.caseStep.active_contract?.provider_contact;
    },

    canUpdate(): boolean {
      if (!isClientContact()) {
        return false;
      }
      if (this.caseStep.state.name == "FREE") {
        return true;
      }
      for (let action of this.caseStep.actions) {
        if (action.name == "client_contact_earmark_case_step") {
          return true;
        }
      }
      return false;
    },
  },

  methods: {
    handleSelect(providerContact: ProviderContactSerializer) {
      const caseStep = Object.assign({}, this.caseStep);
      if (!caseStep.active_contract) {
        caseStep.active_contract = NullCaseStepContract();
      }
      caseStep.active_contract.provider_contact = providerContact;
      this.$emit("update:case-step", caseStep);
      this.state = State.Displaying;
    },
  },
});
</script>
