<template>
  <div class="content section x-scrollable">
    <svg
      v-if="tasks.length > 0"
      v-bind="svgProps"
      id="gantt"
      @click="handleSvgClick"
    >
      <g
        v-for="(task, i) of tasks"
        :key="task.id"
        :transform="`translate(0,${y(i)})`"
        :class="{ unselected: selectedTask && task.id !== selectedTask.id }"
        @click.stop="selectedTask = task"
      >
        <rect
          class="task-rect"
          :height="y.bandwidth() - taskRect.gap"
          :width="x(task.time[1]) - x(task.time[0])"
          :transform="`translate(${x(task.time[0])},0)`"
          rx="5"
          ry="5"
        />
        <text
          class="task-title"
          x="5"
          :y="0.3 * (y.bandwidth() - taskRect.gap)"
          dy="0.35em"
          :transform="`translate(${x(task.time[0])},0)`"
        >
          {{
            task.title.toLowerCase() === "entry"
              ? `🛂 ${task.title}`
              : task.title
          }}
        </text>
        <text
          class="task-text"
          x="5"
          :y="0.7 * (y.bandwidth() - taskRect.gap)"
          dy="0.35em"
          :transform="`translate(${x(task.time[0])},0)`"
        >
          {{ taskTimeDisplay(task) }}
        </text>
      </g>
    </svg>
    <div v-else class="section mb-6" style="text-align: center">
      This process has no steps yet.
    </div>
    <gantt-editor
      :selectedTask="selectedTask"
      :tasks="tasks"
      :process="process"
    />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import * as d3Array from "d3-array";
import * as d3Axis from "d3-axis";
import * as d3Scale from "d3-scale";
import * as d3Selection from "d3-selection";
const d3 = Object.assign({}, d3Array, d3Axis, d3Scale, d3Selection);

import GanttEditor from "./GanttEditor.vue";
import { ProcessRuleSet } from "@/pydantic-autogenerated-interfaces";
import eventBus from "@/event-bus";

export interface Task {
  id: number;
  type: string; // ProcessStepType
  title: string;
  duration: number[]; // TODO: [number, number]
  time: [number, number];
  text: string;
  progress: number;
  dependsOn: number[];
  [key: string]: number | string | number[] | [number, number];
}

function taskTimeDisplay(task: Task): string {
  const [start, end] = task.time.map(Math.round) as [number, number];
  if (task.time[1] > task.time[0]) {
    return `Day ${start + 1} - ${end}`;
  } else {
    return `Day ${start + 1}`;
  }
}

interface Box {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

export default Vue.extend({
  components: { GanttEditor },
  props: {
    tasks: Array as PropType<Task[]>,
    process: Object as PropType<ProcessRuleSet>,
    width: Number,
  },

  data() {
    return {
      taskRect: { height: 50, gap: 10 },
      margin: { left: 20, top: 40, right: 270, bottom: 20 } as Box,
      selectedTask: null as Task | null,
      taskTimeDisplay,
    };
  },

  created() {
    eventBus.$on(
      "update:selected-task",
      (task: Task | null) => (this.selectedTask = task)
    );
  },

  mounted() {
    this.createAxis();
  },

  updated() {
    this.updateAxis();
  },

  methods: {
    handleSvgClick() {
      this.selectedTask = null;
    },

    createAxis() {
      // Horizontal time axis
      d3.select("#gantt")
        .append("g")
        .call(d3.axisTop(this.x))
        .attr("id", "x-axis")
        .attr(
          "transform",
          `translate(0,${this.y.range()[0] - this.margin.top / 2})`
        );
    },

    updateAxis() {
      // https://davidbanks.co.nz/post/transition-d3-axes
      d3.select("#x-axis").call(d3.axisTop(this.x));
    },
  },

  computed: {
    x(): d3Scale.ScaleLinear<number, number, never> {
      const margin = this.margin as Box;
      return d3
        .scaleLinear()
        .domain([0, Math.max(...this.tasks.map((d) => d.time[1] || 0))])
        .range([margin.left, this.width - margin.right]);
    },

    y(): d3Scale.ScaleBand<string> {
      const margin = this.margin as Box;
      return d3
        .scaleBand()
        .domain(d3.range(this.tasks.length) as any)
        .range([
          margin.top,
          margin.top + this.taskRect.height * this.tasks.length,
        ]);
    },

    svgProps(): Record<string, number | string> {
      const margin = this.margin as Box;
      return {
        width: this.width,
        height: this.y.range()[1] + margin.bottom,
        "font-family": "sans-serif",
        "font-size": "10",
        "text-anchor": "start",
      };
    },
  },
});
</script>

<style>
.task-rect {
  fill: #f3f3f3;
  stroke: #cccccc;
  stroke-width: 1;
}
g.unselected {
  opacity: 0.4;
}
.task-title {
  font-weight: bold;
  font-size: 1.3em;
}
.task-progress {
  fill: red;
  stroke: red;
  stroke-width: 1;
}
.x-scrollable {
  overflow-x: scroll;
  -ms-overflow-style: none; /* IE and Edge */
  scrollbar-width: none; /* Firefox */
}
.x-scrollable::-webkit-scrollbar {
  display: none;
}
</style>
