<template>
  <div>
    <gantt-new-task-button :process="process" />
    <div v-if="selectedTask" class="section box mt-3" style="height: 500px">
      <gantt-task-form :task="selectedTask" :tasks="tasks" />
    </div>
    <b-button @click="save" class="is-info" style="float: right">
      Save changes
    </b-button>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { NotificationProgrammatic as Notification } from "buefy";

import GanttTaskForm from "./GanttTaskForm.vue";
import { Task } from "./Gantt.vue";
import GanttNewTaskButton from "./GanttNewTaskButton.vue";
import { ProcessRuleSet } from "@/pydantic-autogenerated-interfaces";
import GanttStepsDiffSummary from "./GanttStepsDiffSummary.vue";
import { makeTask } from "@/components/ProcessStepsGantt.vue";
import { renderComponentToString } from "@/componentUtils";
import http from "@/http";
import eventBus from "@/event-bus";

export default Vue.extend({
  props: {
    selectedTask: Object as PropType<Task>,
    tasks: Array as PropType<Task[]>,
    process: Object as PropType<ProcessRuleSet>,
  },
  components: { GanttTaskForm, GanttNewTaskButton },

  methods: {
    async save() {
      const message = await this.getEditsDescription();
      this.$buefy.dialog.confirm({
        title: "Confirm your changes",
        message,
        cancelText: "Cancel",
        confirmText: "Confirm",
        type: "is-info",
        onConfirm: this.reallySave,
      });
    },

    async reallySave(): Promise<void> {
      const data = await http.postFetchDataOrNull(
        `/api/process/${this.process.id}/`,
        {
          body: JSON.stringify(this.tasks.map((t) => new ProcessStepData(t))),
        }
      );
      if (data === null || data["validation-errors"]) {
        Notification.open({
          message: `Error: process steps not updated: ${
            data ? data["validation-errors"] : ""
          }`,
          type: "is-danger",
          hasIcon: true,
          position: "is-bottom-right",
        });
      } else {
        Notification.open({
          message: "Process steps updated",
          type: "is-success",
          hasIcon: true,
          position: "is-bottom-right",
        });
        // TODO: why is data here the Process and yet we are checking for a
        // validation-errors key above?
        eventBus.$emit("update:process", data);
      }
    },

    async getEditsDescription(): Promise<string> {
      const oldTasks = this.process.step_rulesets.map((sr) =>
        makeTask(sr.process_step)
      );
      const newTasks = this.tasks;
      const vm = new GanttStepsDiffSummary({
        propsData: {
          oldTasks,
          newTasks,
        },
      });
      return await renderComponentToString(vm);
    },
  },
});

class ProcessStepData {
  id: number;
  depends_on_ids: number[];
  step_duration_range: number[];

  constructor(task: Task) {
    this.id = task.id;
    this.depends_on_ids = [...task.dependsOn];
    this.step_duration_range = [...task.duration];
  }
}
</script>
