<template>
  <div class="media">
    <div class="media-left">
      <country :country="case_.process.route.host_country" />
    </div>

    <div class="media-content">
      <p class="title is-size-6">
        {{ case_.process.route.name }}
      </p>
      <case-steps
        v-if="showSteps"
        :steps="case_.steps"
        :process="case_.process"
        :editingSpec="caseSpec.steps"
      />
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { CaseSerializer } from "../autogenerated-interfaces";
import { CaseSpec } from "@/editable-component";
import CaseSteps from "./CaseSteps.vue";
import Country from "./Country.vue";

export default Vue.extend({
  props: {
    case_: Object as PropType<CaseSerializer>,
    caseSpec: Object as PropType<CaseSpec>,
    showSteps: { type: Boolean, default: true },
  },

  components: { CaseSteps, Country },
});
</script>
