<template>
  <div class="section">
    <editable-route :initialCandidateProcesses="processes" :route="route" />
    <process-steps-gantt v-if="process" :process="process" :editable="true" />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import {
  ProcessRuleSet as IProcessRuleSet,
  Route as IRoute,
} from "@/autogenerated-interfaces/immigration";
import ProcessStepsGantt from "@/components/ProcessStepsGantt.vue";
import EditableRoute from "./EditableRoute.vue";
import { NullRoute } from "@/factories";

export default Vue.extend({
  props: {
    processes: Array as PropType<IProcessRuleSet[]>,
    process: Object as PropType<IProcessRuleSet | null>,
  },
  components: { ProcessStepsGantt, EditableRoute },

  computed: {
    route(): IRoute {
      return this.process ? this.process.route : (NullRoute() as IRoute);
    },
  },
});
</script>

<style scoped></style>
