<template>
  <div class="media">
    <div class="media-left">
      <country :country="case_.process.route.host_country" />
    </div>

    <div class="media-content">
      <p class="title is-size-6">
        {{ case_.process.route.name }}
      </p>
      <case-steps
        v-if="showSteps"
        :case_="case_"
        :steps="steps"
        :stepsEditable="caseEditable.steps"
      ></case-steps>
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { CaseSerializer } from "../autogenerated-interfaces";
import CaseSteps from "./CaseSteps.vue";
import Country from "./Country.vue";

export default Vue.extend({
  props: {
    case_: Object as PropType<CaseSerializer>,
    caseEditable: {
      type: Object,
      default: function () {
        return {};
      },
    },
    showSteps: { type: Boolean, default: true },
  },

  components: { CaseSteps, Country },

  computed: {
    steps() {
      return [...this.case_.steps].sort(
        (s, t) => s.sequence_number - t.sequence_number
      );
    },
  },
});
</script>
