<template>
  <b-table
    ref="table"
    :data="rows"
    :paginated="paginated"
    :per-page="10"
    :focusable="focusable"
    :selected.sync="selectedRowProxy"
    @dblclick="(row) => $emit('dblclick', row)"
    hoverable
  >
    <b-table-column
      v-if="columnSpec.nationalitiesRule"
      label="Allowed nationalities"
      v-slot="props"
      :td-attrs="nationalitiesRuleTdAttrs"
    >
      <b-tooltip type="is-info is-light" position="is-right" multilined>
        <div>
          {{ props.row.process.nationalities_description || "." }}
        </div>
        <template v-slot:content>
          <span class="is-size-2">🦉</span>
          {{ nationalitiesRuleTdAttrs(props.row)._explanation }}
        </template>
      </b-tooltip>
    </b-table-column>

    <b-table-column
      v-if="columnSpec.durationRule"
      label="Allowed stay (days)"
      v-slot="props"
      :td-attrs="durationRuleTdAttrs"
    >
      <b-tooltip type="is-info is-light" multilined>
        <div
          v-if="
            durationRuleTdAttrs(props.row)._result ===
            RuleEvaluationResult.DoesNotApply
          "
        >
          .
        </div>
        <div v-else-if="props.row.process.duration_max_days">
          {{ props.row.process.duration_min_days || 0 }} -
          {{ props.row.process.duration_max_days }}
        </div>
        <div v-else>{{ props.row.process.duration_min_days }}+</div>
        <template v-slot:content>
          <span class="is-size-2">🦉</span>
          {{ durationRuleTdAttrs(props.row)._explanation }}
        </template>
      </b-tooltip>
    </b-table-column>

    <b-table-column
      v-if="columnSpec.contractLocationRule"
      label="Contract location"
      v-slot="props"
      :td-attrs="contractLocationRuleTdAttrs"
    >
      <b-tooltip type="is-info is-light" multilined>
        <div
          v-if="
            contractLocationRuleTdAttrs(props.row)._result ===
            RuleEvaluationResult.DoesNotApply
          "
        >
          .
        </div>
        <div v-else>
          {{ props.row.process.contract_location }}
        </div>
        <template v-slot:content>
          <span class="is-size-2">🦉</span>
          {{ contractLocationRuleTdAttrs(props.row)._explanation }}
        </template>
      </b-tooltip>
    </b-table-column>

    <b-table-column
      v-if="columnSpec.payrollLocationRule"
      label="Payroll location"
      v-slot="props"
      :td-attrs="payrollLocationRuleTdAttrs"
    >
      <b-tooltip type="is-info is-light" multilined>
        <div
          v-if="
            payrollLocationRuleTdAttrs(props.row)._result ===
            RuleEvaluationResult.DoesNotApply
          "
        >
          .
        </div>
        <div v-else>
          {{ props.row.process.payroll_location }}
        </div>
        <template v-slot:content>
          <span class="is-size-2">🦉</span>
          {{ payrollLocationRuleTdAttrs(props.row)._explanation }}
        </template>
      </b-tooltip>
    </b-table-column>

    <b-table-column
      v-if="columnSpec.salaryRule"
      label="Annual salary requirement"
      v-slot="props"
      :td-attrs="salaryRuleTdAttrs"
    >
      <b-tooltip type="is-info is-light" multilined>
        <div
          v-if="
            salaryRuleTdAttrs(props.row)._result ===
            RuleEvaluationResult.DoesNotApply
          "
        >
          .
        </div>
        <div v-else>
          {{ props.row.process.minimum_salary }}
          {{ props.row.process.minimum_salary_currency }}
        </div>
        <template v-slot:content>
          <span class="is-size-2">🦉</span>
          {{ salaryRuleTdAttrs(props.row)._explanation }}
        </template>
      </b-tooltip>
    </b-table-column>

    <b-table-column
      label=""
      width="30px"
      :td-attrs="
        () => ({
          style: {
            'border-style': 'none',
          },
        })
      "
      :th-attrs="() => ({ style: { 'border-style': 'none' } })"
    >
      <div></div>
    </b-table-column>

    <b-table-column
      v-if="columnSpec.route"
      label="Route"
      v-slot="props"
      :td-attrs="routeTdAttrs"
    >
      <b-tooltip type="is-info is-light" multilined>
        <editable-route
          :route="props.row.process.route"
          :editingSpec="caseSpec(props.index, 'route')"
        />
        <template v-slot:content>
          <span class="is-size-2">🦉</span>
          {{ routeTdAttrs(props.row)._explanation }}
        </template>
      </b-tooltip>
    </b-table-column>
  </b-table>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { CaseSerializer } from "@/autogenerated-interfaces";
import EditableRoute from "../components/EditableRoute.vue";
import { CaseSpec, EditingSpec } from "@/editable-component";
import { RuleEvaluationResult } from "@/immigration/rules/base";

export default Vue.extend({
  props: {
    rows: Array as PropType<CaseSerializer[]>,
    columnSpec: Object as PropType<CaseSpec>,
    caseSpecs: Array as PropType<CaseSpec[] | null>,
    selected: Object,
    // TODO: focusable must always be true when using `selected`?
    focusable: Boolean,
    paginated: {
      type: Boolean,
      default: false,
    },
    contractLocationRuleTdAttrs: {
      type: Function,
      default: () => ({}),
    },
    durationRuleTdAttrs: {
      type: Function,
      default: () => ({}),
    },
    nationalitiesRuleTdAttrs: {
      type: Function,
      default: () => ({}),
    },
    payrollLocationRuleTdAttrs: {
      type: Function,
      default: () => ({}),
    },
    salaryRuleTdAttrs: {
      type: Function,
      default: () => ({}),
    },
    routeTdAttrs: {
      type: Function,
      default: () => ({}),
    },
  },
  components: {
    EditableRoute,
  },

  data() {
    return {
      selectedRowProxy: {},
      RuleEvaluationResult,
    };
  },

  watch: {
    selectedRowProxy: function (row) {
      // This is slightly convoluted. This component is standing downstream of a
      // view, and upstream of b-table. But the b-table selected row feature
      // doesn't really seem to be designed for that: it requires the use of
      // :selected.sync=x, therefore `x` must be owned data, not the prop that
      // the upstream view has passed in. So, this intermediate component owns
      // some data (this.selectedRowProxy), and that data is updated by the
      // required selected.sync with the downstream b-table, and this watcher
      // notifies the upstream view when the selected row changes.
      this.$emit("update:selected", row);
    },
  },

  methods: {
    caseSpec(index: number, property: string): EditingSpec {
      return (
        (this.caseSpecs &&
          this.caseSpecs[index] &&
          ((this.caseSpecs[index] as CaseSpec)[property] as EditingSpec)) || {
          editable: false,
          disabled: false,
        }
      );
    },
  },
});
</script>

<style>
.table tr.is-selected {
  background-color: #eeeeee !important;
  color: currentColor;
}
</style>
