<template>
  <div class="section">
    <editable-route :initialCandidateProcesses="processes" :route="route" />
    <process-steps-gantt v-if="process" :process="process" />
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { ProcessRuleSet, Route } from "@/pydantic-autogenerated-interfaces";
import ProcessStepsGantt from "@/components/ProcessStepsGantt.vue";
import EditableRoute from "./EditableRoute.vue";
import { NullRoute } from "@/factories";

export default Vue.extend({
  props: {
    processes: Array as PropType<ProcessRuleSet[]>,
    process: Object as PropType<ProcessRuleSet | null>,
  },
  components: { ProcessStepsGantt, EditableRoute },

  computed: {
    route(): Route {
      return this.process ? this.process.route : (NullRoute() as Route);
    },
  },
});
</script>

<style scoped></style>
