<template>
  <div class="media">
    <div class="media-left">
      <img :src="provider.logo_url" width="88px" />
    </div>
    <div v-if="showName" class="media-content">
      <p class="title is-size-6">
        {{ provider.name }}
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { Provider as IProvider } from "@/autogenerated-interfaces/app";
import Vue, { PropType } from "vue";

export default Vue.extend({
  props: {
    provider: Object as PropType<IProvider>,
    editable: {
      type: Boolean,
      default: false,
    },
    showName: {
      type: Boolean,
      default: true,
    },
  },
});
</script>

<style scoped>
a,
a:hover {
  color: currentColor;
}
.media {
  border-top: none;
}
</style>
