<template>
  <div class="field has-addons" style="width: 100%">
    <p class="control" style="width: 100%">
      <b-field :label="label">
        <b-autocomplete
          ref="autocomplete"
          v-model="input"
          field="displayName"
          :data="filteredCandidates"
          @select="
            (providerContact) =>
              $emit('change:provider-contact', providerContact)
          "
          :openOnFocus="true"
          :keep-first="true"
          :placeholder="placeholder"
          dropdown-position="bottom"
          max-height="100vh"
        >
          <template slot-scope="props">
            <provider-contact
              :provider_contact="props.option"
            ></provider-contact>
          </template>
        </b-autocomplete>
      </b-field>
    </p>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { BAutocomplete as BAutocompleteInstance } from "buefy/src/components/autocomplete";
type BAutocomplete = InstanceType<typeof BAutocompleteInstance>;

import { inputMatchesString } from "@/utils";
import {
  ProcessSerializer,
  ProviderContactSerializer,
} from "../autogenerated-interfaces";
import { dismissMobileKeyboardOnDropdownScroll } from "../componentUtils";
import { processIsNull } from "@/factories";
import http from "../http";
import ProviderContact from "./ProviderContact.vue";

export default Vue.extend({
  components: { ProviderContact },
  props: {
    label: String,
    process: Object as PropType<ProcessSerializer>,
    initialProviderContacts: {
      type: Array as PropType<ProviderContactSerializer[]>,
      default: () => [],
    },
    current: {
      type: Object as PropType<ProviderContactSerializer | null>,
      default: null,
    },
    placeholder: String,
  },

  data() {
    return {
      input: "",
      providerContacts: [] as ProviderContactSerializer[],
    };
  },

  created() {
    if (this.initialProviderContacts.length > 0) {
      this.providerContacts = this.initialProviderContacts;
    } else if (!processIsNull(this.process)) {
      this.fetchProviderContacts(this.process);
    }
  },

  mounted() {
    if (this.current) {
      const autocomplete = this.$refs.autocomplete as BAutocomplete;
      autocomplete.setSelected(
        Object.assign(this.current, {
          displayName: displayName(this.current),
        })
      );
    }
    dismissMobileKeyboardOnDropdownScroll(this, "autocomplete");
  },

  watch: {
    process: function (value: ProcessSerializer): void {
      this.fetchProviderContacts(value);
    },
  },

  computed: {
    filteredCandidates(): ProviderContactSerializer[] {
      return this.providerContacts
        .filter((providerContact) =>
          inputMatchesString(this.input, displayName(providerContact))
        )
        .map((providerContact) => {
          return Object.assign(providerContact, {
            displayName: displayName(providerContact),
          });
        });
    },
  },

  methods: {
    fetchProviderContacts(process_: ProcessSerializer) {
      if (!process_.uuid) {
        // TODO: why?
        return;
      }
      http
        .get(
          `/api/client-contact/list-provider-contacts/?process_uuid=${process_.uuid}`
        )
        .then((resp) => resp.json())
        .then((data) => (this.providerContacts = data));
    },
  },
});

function displayName(providerContact: ProviderContactSerializer): string {
  return `${providerContact.user.first_name} ${providerContact.user.last_name} (${providerContact.provider.name})`;
}
</script>
