<template>
  <div class="media">
    <div class="media-left">
      <img :src="provider.logo_url" width="88px" />
    </div>
    <div v-if="showName" class="media-content">
      <p class="title is-size-6">
        {{ provider.name }}
      </p>
    </div>
    <i v-if="providerEditable" class="fas fa-pencil-alt"></i>
  </div>
</template>

<script lang="ts">
import { ProviderSerializer } from "@/autogenerated-interfaces";
import Vue, { PropType } from "vue";

export default Vue.extend({
  props: {
    provider: Object as PropType<ProviderSerializer>,
    providerEditable: {
      type: Boolean,
      default: false,
    },
    showName: {
      type: Boolean,
      default: true,
    },
  },
});
</script>

<style scoped>
a,
a:hover {
  color: currentColor;
}
</style>