<template>
  <div class="media">
    <div class="media-left">
      <country :country="route.host_country" />
    </div>

    <div class="media-content">
      <p class="title is-size-6">
        {{ route.name }}
      </p>
    </div>
    <i v-if="routeEditable" class="fas fa-pencil-alt"></i>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { RouteSerializer } from "../autogenerated-interfaces";
import Country from "./Country.vue";

export default Vue.extend({
  props: {
    route: Object as PropType<RouteSerializer>,
    routeEditable: Boolean,
  },

  components: { Country },
});
</script>
