<template>
  <!-- TODO: This is very similar to Process.vue -->
  <div class="media">
    <div class="media-left">
      <country :country="route.host_country" />
    </div>

    <div class="media-content">
      <p class="title is-size-6">
        {{ route.name }}
        <sup><i v-if="editable" class="fas fa-pencil-alt"></i></sup>
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

import { RouteSerializer } from "../autogenerated-interfaces";
import Country from "./Country.vue";

export default Vue.extend({
  props: {
    route: Object as PropType<RouteSerializer>,
    editable: Boolean,
  },

  components: { Country },
});
</script>
