import { ProcessRuleSet } from "../../pydantic-autogenerated-interfaces";
import { CountrySerializer } from "../../autogenerated-interfaces";

export enum RuleEvaluationResult {
  InsufficientInput,
  DoesNotApply,
  Pass,
  Fail,
}

export enum Rule {
  Nationalities,
  Duration,
  ContractLocation,
  PayrollLocation,
  Salary,
}

export interface IRule {
  processRuleSet: ProcessRuleSet;
  evaluate(
    ...args: (Date | CountrySerializer[] | string | number)[]
  ): { result: RuleEvaluationResult; explanation: string };
}

export class BaseRule {
  processRuleSet: ProcessRuleSet;
  constructor(processRuleSet: ProcessRuleSet) {
    this.processRuleSet = processRuleSet;
  }
}

export enum HomeOrHostCountry {
  HomeCountry = "HOME_COUNTRY",
  HostCountry = "HOST_COUNTRY",
  None = "",
}

export const HomeOrHostCountryDisplayName: Map<
  HomeOrHostCountry,
  string
> = new Map([
  [HomeOrHostCountry.HomeCountry, "Home Country"],
  [HomeOrHostCountry.HostCountry, "Host Country"],
  [HomeOrHostCountry.None, ""],
]);
