import { ProcessRuleSet } from "../../pydantic-autogenerated-interfaces";
import { CountrySerializer } from "../../autogenerated-interfaces";

export enum RuleEvaluationResult {
  InsufficientInput,
  DoesNotApply,
  Pass,
  Fail,
}

export enum Rule {
  Nationalities,
  Duration,
  ContractLocation,
  PayrollLocation,
  Salary,
}

export interface IRule {
  processRuleSet: ProcessRuleSet;
  evaluate(
    ...args: (Date | CountrySerializer[] | string | number)[]
  ): { result: RuleEvaluationResult; explanation: string };
}

export class BaseRule {
  processRuleSet: ProcessRuleSet;
  constructor(processRuleSet: ProcessRuleSet) {
    this.processRuleSet = processRuleSet;
  }
}
