<template>
  <div>
    <section class="section">
      <h1 class="subtitle">
        Describe your move! Matching immigration options will appear below.
      </h1>
      <case :case_="case_" :caseSpec="caseSpec" :showClient="false" />
      <h1 class="subtitle mt-6">Immigration Options</h1>
      <div class="card" style="overflow: visible">
        <case-table
          :rows="matchingProcesses"
          :columnSpec="processSpec"
          :caseSpecs="[processSpec]"
          :focusable="false"
          :paginated="false"
        />
      </div>
    </section>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

import "vue-json-pretty/lib/styles.css";

import {
  CaseSerializer,
  CountrySerializer,
  ProcessSerializer,
} from "@/autogenerated-interfaces";
import Case from "@/components/Case.vue";
import CaseTable from "@/components/CaseTable.vue";
import { CaseSpec } from "@/editable-component";
import { NullCase, NullMove } from "@/factories";
import { dateToYYYYMMDD } from "@/utils";
import eventBus from "@/event-bus";
import http from "@/http";

export default Vue.extend({
  components: {
    Case,
    CaseTable,
  },

  data() {
    return {
      move: NullMove(),
      caseSpec: {
        hostCountry: {
          editable: true,
          disabled: false,
        },
        dateRange: {
          editable: true,
          disabled: false,
        },
      } as CaseSpec,
      matchingProcesses: [] as CaseSerializer[],
      processSpec: {
        route: {
          editable: false,
          disabled: false,
        },
      } as CaseSpec,
    };
  },

  created() {
    // TODO: This global event bus is a bit sketchy. What about if something
    // else is changing a country for some other reason?
    eventBus.$on("update:country", this.handleChangeHostCountry);
    eventBus.$on("update:date-range", this.handleInputDateRange);
  },

  computed: {
    case_(): CaseSerializer {
      return Object.assign(NullCase(), { move: this.move });
    },
  },

  methods: {
    async handleChangeHostCountry(country: CountrySerializer) {
      this.case_.process.route.host_country = country;
      this.move.host_country = country;
      this.fetchMatchingProcesses();
    },

    handleInputDateRange([entryDate, exitDate]: [Date, Date]): void {
      this.move.target_entry_date = dateToYYYYMMDD(entryDate);
      this.move.target_exit_date = dateToYYYYMMDD(exitDate);
      // debugger;
      this.fetchMatchingProcesses();
    },

    async fetchMatchingProcesses(): Promise<void> {
      const matchingProcesses = (await http.postFetchDataOrNull(
        "/api/process/query/",
        {
          body: JSON.stringify(this.move),
        }
      )) as ProcessSerializer[] | null;
      if (matchingProcesses) {
        this.matchingProcesses = matchingProcesses.map((process) =>
          Object.assign(NullCase(), { process })
        );
      }
    },
  },
});
</script>
