<template>
  <div>
    <section class="section">
      <h1 class="subtitle">
        Enter the information for your move. Matching immigration options will
        appear below.
      </h1>
      <case :case_="case_" :caseSpec="caseSpec" :showClient="false" />
      <br />
      <br />
      <div
        v-if="processRuleSets.length > 0"
        class="card mt-6"
        style="overflow: visible"
      >
        <process-ruleset-table
          :rows="processRuleSets"
          :columnSpec="processSpec"
          :caseSpecs="[processSpec]"
          :focusable="false"
          :paginated="false"
          v-bind="makeProcessRuleSetTdAttrs()"
        />
      </div>
    </section>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

import "vue-json-pretty/lib/styles.css";

import {
  ApplicantSerializer,
  CaseSerializer,
  CountrySerializer,
} from "@/autogenerated-interfaces";
import { ProcessRuleSet } from "@/pydantic-autogenerated-interfaces";
import Case from "@/components/Case.vue";
import ProcessRulesetTable from "@/components/ProcessRulesetTable.vue";
import { CaseSpec } from "@/editable-component";
import { NullCase, NullMove } from "@/factories";
import { Rule, RuleEvaluationResult } from "@/immigration/rules/base";
import { ContractLocationRule } from "@/immigration/rules/contract-location";
import { PayrollLocationRule } from "@/immigration/rules/payroll-location";
import { SalaryRule } from "@/immigration/rules/salary";
import { DurationRule } from "@/immigration/rules/duration";
import { NationalitiesRule } from "@/immigration/rules/nationalities";
import { dateToYYYYMMDD, english as en } from "@/utils";
import eventBus from "@/event-bus";
import http from "@/http";

export default Vue.extend({
  components: {
    Case,
    ProcessRulesetTable,
  },

  data() {
    return {
      move: NullMove(),
      caseSpec: {
        hostCountry: {
          editable: true,
          disabled: false,
        },
        applicant: {
          editable: true,
          disabled: false,
        },
        dateRange: {
          editable: true,
          disabled: false,
        },
        contractLocation: {
          editable: true,
          disabled: false,
        },
        payrollLocation: {
          editable: true,
          disabled: false,
        },
        salary: {
          editable: true,
          disabled: false,
        },
      } as CaseSpec,
      processRuleSets: [] as CaseSerializer[],
      processSpec: {
        route: {
          editable: false,
          disabled: false,
        },
        // ProcessRuleSet specs
        contractLocationRule: {
          editable: true,
          disabled: false,
        },
        durationRule: {
          editable: false,
          disabled: false,
        },
        nationalitiesRule: {
          editable: false,
          disabled: false,
        },
        payrollLocationRule: {
          editable: true,
          disabled: false,
        },
        salaryRule: {
          editable: true,
          disabled: false,
        },
      } as CaseSpec,
      targetEntryDate: null as Date | null,
      targetExitDate: null as Date | null,
      ruleEvaluationResults: new Map<string, Map<Rule, RuleEvaluationResult>>(),
      ruleEvaluationResult2CssClass: new Map([
        [
          RuleEvaluationResult.InsufficientInput,
          "has-background-warning-light",
        ],
        [RuleEvaluationResult.DoesNotApply, "has-background-success-light"],
        [RuleEvaluationResult.Pass, "has-background-success-light"],
        [RuleEvaluationResult.Fail, "has-background-danger-light"],
      ]) as Map<RuleEvaluationResult, string>,
      rule2InputFieldName: new Map([
        [Rule.Nationalities, "applicant nationality"],
        [Rule.Duration, "dates"],
        [Rule.ContractLocation, "contract location"],
        [Rule.PayrollLocation, "payroll location"],
        [Rule.Salary, "salary"],
      ]),
      rule2RuleName: new Map([
        [Rule.Nationalities, "applicant nationality"],
        [Rule.Duration, "duration of stay"],
        [Rule.ContractLocation, "contract location"],
        [Rule.PayrollLocation, "payroll location"],
        [Rule.Salary, "salary"],
      ]),
    };
  },

  created() {
    // TODO: This global event bus is a bit sketchy. What about if something
    // else is changing a country for some other reason?
    eventBus.$on("update:country", this.handleUpdateHostCountry);
    eventBus.$on("update:applicant", this.handleUpdateApplicant);
    eventBus.$on("update:date-range", this.handleUpdateDateRange);
    eventBus.$on("update:contract-or-payroll-location", this.handleUpdateValue);
    eventBus.$on("update:salary", this.handleUpdateSalary);
    eventBus.$on("update:text", this.handleUpdateValue);
  },

  computed: {
    case_(): CaseSerializer {
      return Object.assign(NullCase(), { move: this.move });
    },
  },

  methods: {
    async handleUpdateHostCountry(country: CountrySerializer) {
      this.case_.process.route.host_country = country;
      this.move.host_country = country;
      this.fetchProcessRuleSets(country);
    },

    handleUpdateApplicant(applicant: ApplicantSerializer): void {
      // TODO: Support selection of nationality independently from applicant
      this.case_.applicant = applicant;
      this.move.nationalities = applicant.nationalities;
      this.triggerProcessRuleSetsIntersectionCalculations();
    },

    handleUpdateDateRange([entryDate, exitDate]: [Date, Date]): void {
      // TODO: Should be storing Date internally and serializing only when
      // sending data externally.
      this.targetEntryDate = entryDate;
      this.targetExitDate = exitDate;
      this.move.target_entry_date = dateToYYYYMMDD(entryDate);
      this.move.target_exit_date = dateToYYYYMMDD(exitDate);
      this.triggerProcessRuleSetsIntersectionCalculations();
    },

    handleUpdateSalary(salary: number): void {
      this.move.salary = salary;
      this.triggerProcessRuleSetsIntersectionCalculations();
    },

    handleUpdateValue(text: string, id: string): void {
      switch (id) {
        case "contract-location":
          this.move.contract_location = text;
          break;
        case "payroll-location":
          this.move.payroll_location = text;
          break;
      }
      this.triggerProcessRuleSetsIntersectionCalculations();
    },

    triggerProcessRuleSetsIntersectionCalculations(): void {
      // Force reactive re-rendering of the process ruleset table so that the
      // rule calculations are performed and thus the table cells are styled
      // according to whether the current Move intersects with the rules.
      this.processRuleSets = [...this.processRuleSets];
    },

    async fetchProcessRuleSets(country: CountrySerializer): Promise<void> {
      this.processRuleSets = [];
      this.ruleEvaluationResults = new Map();
      const processRuleSets = (await http.fetchDataOrNull(
        `/api/processruleset/${country.code}`
      )) as ProcessRuleSet[] | null;
      if (processRuleSets) {
        for (const process of processRuleSets) {
          this.processRuleSets.push(Object.assign(NullCase(), { process }));
          this.ruleEvaluationResults.set(
            process.uuid,
            new Map([
              [Rule.Nationalities, RuleEvaluationResult.InsufficientInput],
              [Rule.Duration, RuleEvaluationResult.InsufficientInput],
              [Rule.ContractLocation, RuleEvaluationResult.InsufficientInput],
              [Rule.PayrollLocation, RuleEvaluationResult.InsufficientInput],
              [Rule.Salary, RuleEvaluationResult.InsufficientInput],
            ])
          );
        }
      }
    },

    /// Buefy table td-attrs function, see https://buefy.org/documentation/table/#api-view
    makeProcessRuleSetTdAttrs(): Record<string, (prs: CaseSerializer) => void> {
      return {
        contractLocationRuleTdAttrs: this.contractLocationRuleTdAttrs,
        durationRuleTdAttrs: this.durationRuleTdAttrs,
        nationalitiesRuleTdAttrs: this.nationalitiesRuleTdAttrs,
        payrollLocationRuleTdAttrs: this.payrollLocationRuleTdAttrs,
        salaryRuleTdAttrs: this.salaryRuleTdAttrs,
        routeTdAttrs: this.routeTdAttrs,
      };
    },

    /// Buefy table td-attrs function, see https://buefy.org/documentation/table/#api-view
    durationRuleTdAttrs(
      row: CaseSerializer
    ): Record<string, string | RuleEvaluationResult> {
      const processRuleSet = (row.process as unknown) as ProcessRuleSet;
      const rule = new DurationRule(processRuleSet);
      const { result, explanation } = rule.evaluate(
        this.targetEntryDate as Date,
        this.targetExitDate as Date
      );
      this.ruleEvaluationResults
        .get(processRuleSet.uuid)
        ?.set(Rule.Duration, result);
      return {
        class: this.ruleEvaluationResult2CssClass.get(result) as string,
        _result: result,
        _explanation: explanation,
      };
    },

    /// Buefy table td-attrs function, see https://buefy.org/documentation/table/#api-view
    nationalitiesRuleTdAttrs(
      row: CaseSerializer
    ): Record<string, string | RuleEvaluationResult> {
      const processRuleSet = (row.process as unknown) as ProcessRuleSet;
      const rule = new NationalitiesRule(processRuleSet);
      const { result, explanation } = rule.evaluate(
        this.move.nationalities || [],
        processRuleSet.nationalities_description as string
      );
      this.ruleEvaluationResults
        .get(processRuleSet.uuid)
        ?.set(Rule.Nationalities, result);
      return {
        class: this.ruleEvaluationResult2CssClass.get(result) as string,
        _result: result,
        _explanation: explanation,
      };
    },

    /// Buefy table td-attrs function, see https://buefy.org/documentation/table/#api-view
    contractLocationRuleTdAttrs(
      row: CaseSerializer
    ): Record<string, string | RuleEvaluationResult> {
      const processRuleSet = (row.process as unknown) as ProcessRuleSet;
      const rule = new ContractLocationRule(processRuleSet);
      const { result, explanation } = rule.evaluate(
        this.move.contract_location || ""
      );
      this.ruleEvaluationResults
        .get(processRuleSet.uuid)
        ?.set(Rule.ContractLocation, result);
      return {
        class: this.ruleEvaluationResult2CssClass.get(result) as string,
        _result: result,
        _explanation: explanation,
      };
    },

    /// Buefy table td-attrs function, see https://buefy.org/documentation/table/#api-view
    payrollLocationRuleTdAttrs(
      row: CaseSerializer
    ): Record<string, string | RuleEvaluationResult> {
      const processRuleSet = (row.process as unknown) as ProcessRuleSet;
      const rule = new PayrollLocationRule(processRuleSet);
      const { result, explanation } = rule.evaluate(
        this.move.payroll_location || ""
      );
      this.ruleEvaluationResults
        .get(processRuleSet.uuid)
        ?.set(Rule.PayrollLocation, result);
      return {
        class: this.ruleEvaluationResult2CssClass.get(result) as string,
        _result: result,
        _explanation: explanation,
      };
    },

    /// Buefy table td-attrs function, see https://buefy.org/documentation/table/#api-view
    salaryRuleTdAttrs(
      row: CaseSerializer
    ): Record<string, string | RuleEvaluationResult> {
      const processRuleSet = (row.process as unknown) as ProcessRuleSet;
      const rule = new SalaryRule(processRuleSet);
      const { result, explanation } = rule.evaluate(
        this.move.salary || 0.0,
        this.move.salary_currency || "<no currency supplied>"
      );
      this.ruleEvaluationResults
        .get(processRuleSet.uuid)
        ?.set(Rule.Salary, result);
      return {
        class: this.ruleEvaluationResult2CssClass.get(result) as string,
        _result: result,
        _explanation: explanation,
      };
    },

    /// Buefy table td-attrs function, see https://buefy.org/documentation/table/#api-view
    routeTdAttrs(
      row: CaseSerializer
    ): Record<string, string | RuleEvaluationResult | Record<string, string>> {
      const processRuleSet = (row.process as unknown) as ProcessRuleSet;
      const result2rules = new Map<RuleEvaluationResult, Rule[]>();
      const ruleEvaluationResults =
        this.ruleEvaluationResults.get(processRuleSet.uuid)?.entries() || [];
      let _result, _explanation;
      for (const [rule, result] of ruleEvaluationResults) {
        if (!result2rules.has(result)) {
          result2rules.set(result, []);
        }
        result2rules.get(result)?.push(rule);
      }
      const fail = (result2rules.get(RuleEvaluationResult.Fail) ||
        []) as Rule[];
      const insufficientInput = (result2rules.get(
        RuleEvaluationResult.InsufficientInput
      ) || []) as Rule[];
      const pass = (result2rules.get(RuleEvaluationResult.Pass) ||
        []) as Rule[];

      if (fail.length > 0) {
        // Input data violates one or more rules.
        _result = RuleEvaluationResult.Fail;
        _explanation = `This immigration route is not available because ${en.q(
          fail.length,
          "requirement was",
          "requirements were"
        )} not satisfied by the information you've entered: ${this.enListRules(
          fail
        )}.`;
      } else if (insufficientInput.length > 0) {
        // Input data passes, but there is a field with a rule that the user hasn't filled out.
        _result = RuleEvaluationResult.InsufficientInput;
        _explanation = `I don't know for sure whether this immigration route is available \
because you have not entered the ${this.enListFields(insufficientInput)}.`;
      } else if (pass.length > 0) {
        _result = RuleEvaluationResult.Pass;
        _explanation = `This immigration route is available to you: it has requirements for \
${this.enListRules(
  pass
)}, and the information you've entered meets those requirements.`;
      } else {
        // Input passes vacuously, i.e. this immigration route has no rules.
        _result = RuleEvaluationResult.Pass;
        _explanation =
          "This immigration route doesn't have any requirements, so it's an option.";
      }
      return {
        class: this.ruleEvaluationResult2CssClass.get(_result) as string,
        _result,
        _explanation,
        style: {},
      };
    },
    enListFields(rules: Rule[]): string {
      return en.list(
        rules.map((r) => this.rule2InputFieldName.get(r) as string)
      );
    },
    enListRules(rules: Rule[]): string {
      return en.list(rules.map((r) => this.rule2RuleName.get(r) as string));
    },
  },
});
</script>
