<template>
  <section class="section">
    <case :case_="case_" v-if="case_"></case>
  </section>
</template>

<script lang="ts">
import Vue from "vue";

import { CaseSerializer } from "../autogenerated-interfaces";
import Case from "../components/Case.vue";
import http from "../http";

export default Vue.extend({
  components: { Case },

  data() {
    return {
      case_: null as CaseSerializer | null,
    };
  },

  created() {
    http
      .get(`/api/client-contact/case/${this.$route.params.uuid}/`)
      .then((resp) => resp.json())
      .then((data) => (this.case_ = data));
  },
});
</script>
