<template>
  <div>
    <section class="section">
      <b-field label="Where do you need to send people?">
        <editable-country
          :country="hostCountry"
          :editingSpec="{ editable: true, disabled: false }"
          :showName="true"
        />
      </b-field>

      <b-field label="When?" class="date-range-selector">
        <b-datepicker
          placeholder="Select date range"
          :range="true"
          :mobile-native="false"
          @input="handleInputDateRange"
        />
      </b-field>

      <b-field label="What are they going to do there?">
        <occupation-selector
          :occupation="occupation"
          :candidateOccupations="candidateOccupations"
          :editingSpec="{ editable: true, disabled: false }"
        />
      </b-field>

      <div class="form pt-6">
        <fieldset>
          <div class="field is-grouped pt-4">
            <div class="control">
              <button
                class="button is-link"
                ref="submitButton"
                @click="handleSubmit"
              >
                Find out what's needed!
              </button>
            </div>
          </div>
        </fieldset>
      </div>
    </section>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

import { NotificationProgrammatic as Notification } from "buefy";

import {
  CountrySerializer,
  OccupationSerializer,
} from "@/autogenerated-interfaces";
import EditableCountry from "@/components/EditableCountry.vue";
import OccupationSelector from "@/components/OccupationSelector.vue";
import { NullCountry } from "@/factories";
import http from "@/http";
import { showMessages } from "@/server-messages";
import eventBus from "@/event-bus";

export default Vue.extend({
  components: {
    EditableCountry,
    OccupationSelector,
  },

  data() {
    return {
      hostCountry: NullCountry(),
      occupation: {} as OccupationSerializer,
      candidateOccupations: [] as OccupationSerializer[],
      scenario: {},
      validationErrors: null as Record<string, string[]> | null,
    };
  },

  async created() {
    eventBus.$on("update:country", this.handleUpdateCountry);
    eventBus.$on("update:occupation", this.handleUpdateOccupation);
    this.candidateOccupations =
      (await http.fetchDataOrNull("/api/occupations/")) || [];
  },

  methods: {
    handleUpdateCountry(country: CountrySerializer) {
      this.hostCountry = country;
    },

    handleUpdateOccupation(occupation: OccupationSerializer) {
      this.occupation = occupation;
    },

    handleInputDateRange([entryDate, exitDate]: [Date, Date]): void {
      null;
    },

    async handleSubmit(): Promise<void> {
      // TODO: validation
      const httpResponse = await http.post("/api/immigration/assessment/", {
        body: JSON.stringify(this.scenario),
      });
      if (httpResponse.ok) {
        const response = await httpResponse.json();
        showMessages(response);
        if (response.errors.length > 0) {
          this.validationErrors = response.errors;
        } else {
          const message = `Success! Assignment response received: ${response.data}`;
          Notification.open({
            message,
            type: "is-success",
            hasIcon: true,
            position: "is-bottom-right",
          });
        }
      }
    },
  },
});
</script>

