<template>
  <div>
    <p class="m-4 is-size-2">Case</p>
    <case :case_="case_" v-if="case_"></case>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

import {
  CaseSerializer,
  CaseStepSerializer,
} from "../autogenerated-interfaces";
import Case from "../components/Case.vue";
import http from "../http";
import eventBus from "../event-bus";

export default Vue.extend({
  components: { Case },

  data() {
    return {
      case_: null as CaseSerializer | null,
    };
  },

  async created() {
    this.case_ = await http.fetchDataOrNull(
      `/api/client-contact/case/${this.$route.params.uuid}/`
    );
  },

  mounted() {
    eventBus.$on("update:case", this.updateCaseStep);
  },

  methods: {
    updateCaseStep(index: number, caseStep: CaseStepSerializer) {
      if (this.case_) {
        if (caseStep) {
          this.case_.steps.splice(index, 1, caseStep);
        } else {
          this.case_.steps.splice(index, 1);
        }
      }
    },
  },
});
</script>
