<template>
  <process-gantts v-if="processes" :processes="processes" :process="process" />
</template>

<script lang="ts">
import Vue from "vue";

import ProcessGantts from "@/components/ProcessGantts.vue";
import { ProcessRuleSet } from "@/pydantic-autogenerated-interfaces";
import eventBus from "@/event-bus";
import http from "../http";

export default Vue.extend({
  props: { countryCode: String, processIdString: String },
  components: { ProcessGantts },
  data() {
    return {
      processes: [] as ProcessRuleSet[],
      processId: parseInt(this.processIdString) || null,
    };
  },

  computed: {
    process(): ProcessRuleSet | null {
      if (this.processId) {
        for (const process of this.processes) {
          if (process.id === this.processId) {
            return process;
          }
        }
      }
      return null;
    },
  },

  async created() {
    eventBus.$on("update:process", this.updateProcess);
    this.processes = (await http.fetchDataOrNull(
      `/api/processes/${this.countryCode}/`
    )) as ProcessRuleSet[];
  },

  methods: {
    updateProcess(process: ProcessRuleSet) {
      if (!this.processId || this.processId !== process.id) {
        this.$router.push(
          `/portal/processes/${process.route.host_country.code}/${process.id}/`
        );
      }
      this.processId = process.id;
    },
  },
});
</script>
