<template>
  <process-steps-gantt :steps="steps" :width="1000" />
</template>

<script lang="ts">
import Vue from "vue";

import ProcessStepsGantt from "@/components/ProcessStepsGantt.vue";
import http from "../http";
import {
  ProcessStepRuleSet,
  ProcessRuleSet,
} from "@/pydantic-autogenerated-interfaces";

export default Vue.extend({
  props: { id: String },
  components: { ProcessStepsGantt },
  data() {
    return {
      steps: [] as ProcessStepRuleSet[],
    };
  },

  async created(): Promise<void> {
    const process = (await http.fetchDataOrNull(
      `/api/process/${this.id}`
    )) as ProcessRuleSet;
    this.steps = process ? process.step_rulesets : ([] as ProcessStepRuleSet[]);
  },
});
</script>
