<template>
  <div>
    <p class="m-4 is-size-2">Case</p>
    <case :case_="case_" v-if="case_"></case>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

import { Case as ICase } from "../autogenerated-interfaces/client";
import Case from "../components/Case.vue";
import http from "../http";

export default Vue.extend({
  components: { Case },

  data() {
    return {
      case_: null as ICase | null,
    };
  },

  async created() {
    this.case_ = await http.fetchDataOrNull(
      `/api/provider-contact/case/${this.$route.params.uuid}/`
    );
  },
});
</script>
