<template>
  <div>
    <section class="section">
      <h1 class="subtitle">
        Describe your move! Matching immigration options will appear below.
      </h1>
      <case :case_="move" :caseSpec="moveSpec" :showClient="false" />
      <h1 class="subtitle mt-6">Immigration Options</h1>
      <div class="card" style="overflow: visible">
        <case-table
          :rows="matchingProcesses"
          :columnSpec="processSpec"
          :caseSpecs="[processSpec]"
          :focusable="false"
          :paginated="false"
        />
      </div>
    </section>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

import "vue-json-pretty/lib/styles.css";

import {
  CaseSerializer,
  CountrySerializer,
  ProcessSerializer,
} from "@/autogenerated-interfaces";
import Case from "@/components/Case.vue";
import CaseTable from "@/components/CaseTable.vue";
import { CaseSpec } from "@/editable-component";
import { NullCase } from "@/factories";
import { dateToYYYYMMDD } from "@/utils";
import eventBus from "@/event-bus";
import http from "@/http";

export default Vue.extend({
  components: {
    Case,
    CaseTable,
  },

  data() {
    return {
      move: NullCase(),
      moveSpec: {
        hostCountry: {
          editable: true,
          disabled: false,
        },
        dateRange: {
          editable: true,
          disabled: false,
        },
      } as CaseSpec,
      matchingProcesses: [] as CaseSerializer[],
      processSpec: {
        route: {
          editable: false,
          disabled: false,
        },
      } as CaseSpec,
    };
  },

  created() {
    // TODO: This global event bus is a bit sketchy. What about if something
    // else is changing a country for some other reason?
    eventBus.$on("update:country", this.handleChangeHostCountry);
    eventBus.$on("update:date-range", this.handleInputDateRange);
  },

  methods: {
    async handleChangeHostCountry(country: CountrySerializer) {
      if (!country) {
        // FIXME: why
        console.log("ERROR: country is", JSON.stringify(country));
        return;
      }
      this.move.process.route.host_country = country;

      // HACK ------------------------------------
      /* eslint-disable @typescript-eslint/no-explicit-any */

      const moveSerializerData = Object.assign(
        { host_country: country },
        this.move
      ) as Record<string, any>;
      if (!moveSerializerData.target_entry_date) {
        moveSerializerData.target_entry_date = null;
      }
      if (!moveSerializerData.target_exit_date) {
        moveSerializerData.target_exit_date = null;
      }
      /* eslint-enable @typescript-eslint/no-explicit-any */
      // -----------------------------------------

      const matchingProcesses = (await http.postFetchDataOrNull(
        "/api/process/query/",
        {
          body: JSON.stringify(moveSerializerData),
        }
      )) as ProcessSerializer[] | null;
      if (matchingProcesses) {
        this.matchingProcesses = matchingProcesses.map((process) =>
          Object.assign(NullCase(), { process })
        );
      }
    },

    handleInputDateRange([entryDate, exitDate]: [Date, Date]): void {
      this.move.target_entry_date = dateToYYYYMMDD(entryDate);
      this.move.target_exit_date = dateToYYYYMMDD(exitDate);
    },
  },
});
</script>
