# Generated by Django 3.2 on 2021-05-05 22:25

from django.db import migrations

from immigration.data.load_europe_services import load_europe_services


def forwards(apps, schema_editor):
    Country = apps.get_model("app", "Country")
    ProcessRuleSet = apps.get_model("immigration", "ProcessRuleSet")
    ProcessStep = apps.get_model("immigration", "ProcessStep")
    Route = apps.get_model("immigration", "Route")
    ServiceItem = apps.get_model("immigration", "ServiceItem")
    load_europe_services(
        Country,
        ProcessRuleSet,
        ProcessStep,
        Route,
        ServiceItem,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0003_serviceitem"),
    ]

    operations = [migrations.RunPython(forwards)]
