# Generated by Django 3.2 on 2021-05-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='government_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Government fee in host country currency'),
        ),
    ]
