# Generated by Django 3.2 on 2021-05-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0004_auto_20210505_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='process_step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='immigration.processstep'),
        ),
    ]
