# Generated by Django 3.2 on 2021-05-05 22:53

from django.db import migrations

from app.fixtures.country import load_country_fixture
from immigration.data.load_europe_services import load_europe_services


def forwards(apps, schema_editor):
    Country = apps.get_model("app", "Country")
    ProcessRuleSet = apps.get_model("immigration", "ProcessRuleSet")
    ProcessStep = apps.get_model("immigration", "ProcessStep")
    Route = apps.get_model("immigration", "Route")
    ServiceItem = apps.get_model("immigration", "ServiceItem")
    load_country_fixture()
    load_europe_services(
        Country,
        ProcessRuleSet,
        ProcessStep,
        Route,
        ServiceItem,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0004_auto_20210505_2253"),
    ]

    # This migration was run in production, but is now an annoyance when
    # creating the test db.
    operations = []
