# Generated by Django 3.2 on 2021-05-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0005_load_europe_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processstep',
            options={'ordering': ['sequence_number']},
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='process_step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='immigration.processstep'),
        ),
    ]
