# Generated by Django 3.2 on 2021-05-07 22:54

from django.db import migrations

from immigration.management.commands.datamigration_process_steps import (
    datamigration_process_steps,
)


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0007_auto_20210507_2257"),
    ]

    operations = [migrations.RunPython(datamigration_process_steps)]
