# Generated by Django 3.2 on 2021-05-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0007_auto_20210507_2257"),
    ]

    # Operations deleted after running migration
    operations = []
