# Generated by Django 3.2 on 2021-05-08 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210507_1629'),
        ('immigration', '0008_datamigration_populate_processrulesetstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='host_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
    ]
