# Generated by Django 3.2 on 2021-05-08 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bloc_countries'),
        ('immigration', '0010_auto_20210508_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='host_country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
            preserve_default=False,
        ),
    ]
