# Generated by Django 3.2 on 2021-05-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0011_alter_processstep_host_country'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processstep',
            name='imm__process_step__name__uniq',
        ),
        migrations.RenameField(
            model_name='processstep',
            old_name='process_rule_set',
            new_name='process_ruleset',
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(fields=('process_ruleset', 'name'), name='imm__process_step__name__uniq'),
        ),
    ]
