# Generated by Django 3.2 on 2021-05-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0013_remove_processstep_process_ruleset'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processstep',
            name='imm__process_step__name__uniq',
        ),
    ]
