# Generated by Django 3.2 on 2021-05-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0013_remove_processstep_process_ruleset'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processstep',
            name='imm__process_step__name__uniq',
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='name',
            field=models.CharField(default='', help_text='Name of this issued document.', max_length=128),
        ),
    ]
