# Generated by Django 3.2 on 2021-05-12 01:52

from django.db import migrations


def populate_issued_document_name(apps, _):
    IssuedDocument = apps.get_model("immigration", "IssuedDocument")
    for id in IssuedDocument.objects.select_related("issued_document_type"):
        id.name = id.issued_document_type.name
        id.save()


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0014_auto_20210512_0144"),
    ]

    operations = [migrations.RunPython(populate_issued_document_name)]
