# Generated by Django 3.2 on 2021-05-12 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_bloc_countries"),
        ("immigration", "0015_populate_issued_document_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processstep",
            name="issued_documents",
        ),
        migrations.AddField(
            model_name="issueddocument",
            name="host_country",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.country"
            ),
        ),
        migrations.AlterField(
            model_name="issueddocument",
            name="name",
            field=models.CharField(
                help_text="Name of this issued document.", max_length=128
            ),
        ),
    ]
