# Generated by Django 3.2 on 2021-05-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0016_auto_20210512_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='issued_documents',
            field=models.ManyToManyField(blank=True, help_text='Issued documents associated with this process step.', to='immigration.IssuedDocument'),
        ),
    ]
