# Generated by Django 3.2 on 2021-05-12 02:37

from django.db import migrations


def populate_issued_document_m2m(apps, _):
    IssuedDocument = apps.get_model("immigration", "IssuedDocument")
    for issued_document in IssuedDocument.objects.select_related("process_step"):
        process_step = issued_document.process_step
        process_step.issued_documents.add(issued_document)
        issued_document.host_country = process_step.host_country
        issued_document.save()

class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0017_auto_20210512_0237'),
    ]

    operations = [migrations.RunPython(populate_issued_document_m2m)]
