# Generated by Django 3.2 on 2021-05-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0019_auto_20210512_0318"),
    ]

    operations = [
        migrations.AddField(
            model_name="processruleset",
            name="data_entry_status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not Started"),
                    ("Draft", "Draft"),
                    ("Final", "Final"),
                ],
                default="Not started",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="processstep",
            name="government_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Government fee in host country currency",
                max_digits=9,
                null=True,
            ),
        ),
    ]
