# Generated by Django 3.2 on 2021-05-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0021_auto_20210512_1251"),
    ]

    operations = [
        migrations.AddField(
            model_name="processstep",
            name="applicant_can_enter_host_country_on",
            field=models.CharField(
                blank=True,
                choices=[("Application", "Application"), ("Completion", "Completion")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processstep",
            name="applicant_can_work_in_host_country_on",
            field=models.CharField(
                blank=True,
                choices=[("Application", "Application"), ("Completion", "Completion")],
                max_length=16,
                null=True,
            ),
        ),
    ]
