# Generated by Django 3.2 on 2021-05-12 16:41

from django.db import migrations
from django.db.models import TextChoices


class RightConferredOn(TextChoices):
    APPLICATION = "Application"
    COMPLETION = "Completion"


def populate(apps, _):
    ProcessStep = apps.get_model("immigration", "ProcessStep")
    for ps in ProcessStep.objects.all():
        if ps.applicant_can_enter_host_country_after:
            ps.applicant_can_enter_host_country_on = RightConferredOn.COMPLETION
        if ps.applicant_can_work_in_host_country_after:
            ps.applicant_can_work_in_host_country_on = RightConferredOn.COMPLETION
        ps.save()


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0022_auto_20210512_1641"),
    ]

    operations = [migrations.RunPython(populate)]
