# Generated by Django 3.2 on 2021-05-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0023_populate_rights_conferred_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processstep",
            old_name="required_only_if_duration_exceeds",
            new_name="required_only_if_duration_greater_than",
        ),
        migrations.AlterField(
            model_name="processstep",
            name="required_only_if_duration_greater_than",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum visit duration (days) triggering requirement for this step. Blank means no minimum duration condition.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processstep",
            name="required_only_if_duration_less_than",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum visit duration (days) triggering requirement for this step. Blank means no maximum duration condition.",
                null=True,
            ),
        ),
    ]
