# Generated by Django 3.2 on 2021-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bloc_countries'),
        ('immigration', '0024_auto_20210512_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueddocument',
            name='proves_right_to_travel_in',
            field=models.ManyToManyField(blank=True, help_text='Countries to which the holder of the document may travel. Blank means no travel rights to other countries conferred by document.', related_name='_immigration_issueddocument_proves_right_to_travel_in_+', to='app.Country'),
        ),
    ]
