# Generated by Django 3.2 on 2021-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_bloc_countries"),
        ("immigration", "0027_auto_20210513_0402"),
    ]

    operations = [
        migrations.AddField(
            model_name="processstep",
            name="required_only_if_home_country",
            field=models.ManyToManyField(
                blank=True,
                help_text="Applicant home countries triggering requirement for this step. Blank means no home country condition.",
                related_name="_immigration_processstep_required_only_if_home_country_+",
                to="app.Country",
            ),
        ),
    ]
