# Generated by Django 3.2 on 2021-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0028_auto_20210513_1154"),
    ]

    operations = [
        migrations.AddField(
            model_name="processstep",
            name="required_only_if_contract_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOME_COUNTRY", "Home Country"),
                    ("HOST_COUNTRY", "Host Country"),
                ],
                help_text="Contract location triggering requirement for this step. Blank means no contract location condition.",
                max_length=16,
                null=True,
            ),
        ),
    ]
