# Generated by Django 3.2 on 2021-05-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0029_auto_20210513_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processruleset",
            name="route",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="immigration.route"
            ),
        ),
    ]
