# Generated by Django 3.2 on 2021-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0032_auto_20210515_1633"),
    ]

    operations = [
        migrations.AddField(
            model_name="processstep",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True,
                help_text="Steps on which this step depends directly.",
                to="immigration.ProcessStep",
            ),
        ),
        migrations.AddField(
            model_name="processstep",
            name="is_primary",
            field=models.BooleanField(
                default=True,
                help_text="Is this a 'primary step', i.e., one of the top-level immigration steps all of which will normally be handled by the same provider?",
            ),
            preserve_default=False,
        ),
    ]
