# Generated by Django 3.2 on 2021-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0034_auto_20210524_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="processstep",
            name="type",
            field=models.CharField(
                choices=[
                    ("Primary", "Primary"),
                    ("Ancillary", "Ancillary"),
                    ("Event", "Event"),
                ],
                default="Primary",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
