# Generated by Django 3.2 on 2021-06-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0036_auto_20210526_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processrulesetstep",
            name="sequence_number",
            field=models.PositiveIntegerField(
                help_text="Order of this step relative to other steps of this process.",
                null=True,
            ),
        )
    ]
