# Generated by Django 3.2 on 2021-06-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0037_auto_20210602_1519"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processrulesetstep",
            name="sequence_number",
        ),
    ]
