# Generated by Django 3.2 on 2021-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immigration", "0038_auto_20210602_1945"),
    ]

    operations = [
        migrations.AddField(
            model_name="processstep",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("Principal", "Principal"),
                    ("Principal and dependents", "Principal And Dependents"),
                    ("Dependents", "Dependents"),
                ],
                default="Principal",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="processstep",
            name="type",
            field=models.CharField(
                choices=[
                    ("Primary", "Primary"),
                    ("Ancillary", "Ancillary"),
                    ("Event", "Event"),
                    ("ΤΕΛΟΣ", "Τελος"),
                ],
                max_length=16,
            ),
        ),
    ]
