# Generated by Django 3.1.7 on 2021-03-13 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("home_country", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="PersonImmigrationTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_type", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField()),
                ("current_status", models.CharField(max_length=128)),
                ("host_country", models.CharField(max_length=128)),
                ("progress", models.FloatField()),
                ("service", models.CharField(max_length=128)),
                ("target_entry_date", models.DateField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.person"
                    ),
                ),
            ],
        ),
    ]
