# Generated by Django 3.2 on 2021-05-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='service',
        ),
        migrations.RemoveField(
            model_name='route',
            name='host_country',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='routes',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='ProcessStep',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
