# Generated by Django 3.2 on 2021-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration', '0006_auto_20210507_1309'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='service',
        ),
        migrations.RemoveField(
            model_name='route',
            name='host_country',
        ),
        migrations.AlterField(
            model_name='provider',
            name='routes',
            field=models.ManyToManyField(related_name='providers', to='immigration.Route'),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='ProcessStep',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
