# Generated by Django 3.2 on 2021-05-08 19:22

from django.db import migrations

EU_COUNTRY_NAMES = [
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
]
assert len(EU_COUNTRY_NAMES) == 27


def create_blocs(apps, _):
    Bloc = apps.get_model("app", "Bloc")
    Country = apps.get_model("app", "Country")
    # EU
    eu = Bloc.objects.create(name="EU")
    for country_name in EU_COUNTRY_NAMES:
        eu.countries.add(Country.objects.get(name=country_name))
    # Non-EU
    non_eu = Bloc.objects.create(name="non-EU")
    for country in Country.objects.exclude(name__in=EU_COUNTRY_NAMES):
        non_eu.countries.add(country)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_bloc"),
        ("immigration", "0005_load_europe_services"),
    ]

    operations = [migrations.RunPython(create_blocs)]
