# Generated by Django 3.2 on 2021-05-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_create_blocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='countries',
            field=models.ManyToManyField(blank=True, to='app.Country'),
        ),
    ]
