# Generated by Django 3.2 on 2021-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_country_immigration_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="For Owldock demo purposes: Should this Country appear as an option in UIs?",
            ),
            preserve_default=False,
        ),
    ]
