# Generated by Django 3.2 on 2021-06-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_country_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, help_text='For Owldock demo purposes: Should this Country appear as an option in UIs?'),
        ),
    ]
